CREATE TABLE ZONA_CIUDAD(
ID_ZONA_CIUDAD int(11) NOT NULL AUTO_INCREMENT,
DESCRIPCION_ZONA_CIUDAD VARCHAR(150) NOT NULL default '',
FLAG_ESTADO VARCHAR(2) NOT NULL default 'SI',
PRIMARY KEY (ID_ZONA_CIUDAD)
)ENGINE=InnoDB;

insert into ZONA_CIUDAD(DESCRIPCION_ZONA_CIUDAD,FLAG_ESTADO) values('ZONA DEL SISTEMA','SI');
ALTER TABLE CLIENTE ADD ID_ZONA_CIUDAD int(11) NOT NULL default 1;

ALTER TABLE CLIENTE ADD CONSTRAINT fk_zona FOREIGN KEY (ID_ZONA_CIUDAD) REFERENCES ZONA_CIUDAD (ID_ZONA_CIUDAD);
