/* CREADO PARA CODIGO DE BARRAS */
CREATE TABLE VENTA_RAPIDA(
ID_VENTA_RAPIDA INT(11) NOT NULL AUTO_INCREMENT,
FECHA_VENTA CHAR(10) NOT NULL ,
ID_TIENDA int(11) NOT NULL,
ID_CLIENTE int(11) NOT NULL,
ID_PRODUCTO INT(11) NOT NULL,
PRECIO_VENTA DECIMAL (9,2) NOT NULL,
PRIMARY KEY (ID_VENTA_RAPIDA),
FOREIGN KEY (ID_TIENDA) REFERENCES TIENDA (ID_TIENDA),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
)ENGINE=InnoDB;