


drop TRIGGER inserta_inventarios_sistema;

DELIMITER //
CREATE TRIGGER inserta_inventarios_sistema
 AFTER INSERT ON INVENTARIO_INICIAL_SISTEMA
/*
usa este detalle, para que uses el ID_VENTA, a traves de eso vas a poder actualizar un campo
en la venta que se llame : Utilidad y que sea la resta del costo en almacen entre el precio de venta
*/
 FOR EACH ROW
 BEGIN
declare x int(11) default 0;
declare id_ int(11) default 0;


/*
agregado para las salidas en almacen
*/
DECLARE id_cliente  int(11) default 0;
DECLARE id_producto  int(11) default 0;
DECLARE id_ubicacion int(11) default 0;


DECLARE id_deta  int(50);
DECLARE _cant int(10);
DECLARE _resto int(10);
DECLARE _ID_TIENDA  INT(11);
DECLARE err_no_more_records CONDITION FOR 1329;
DECLARE c CURSOR FOR 


select IFS.ID_INVENTARIO_FISICO as ID,T.ID_TIENDA AS TIENDA, UBF.ID_UBICACION_FISICA AS UBICACION
,P.ID_PRODUCTO AS PRODUCTO, SUM(DUFP.CANTIDAD) as CANTIDAD
from INVENTARIO_FISICO IFS
INNER JOIN DETALLE_INVENTARIO_UBICACION_FISICA DIUF
ON IFS.ID_INVENTARIO_FISICO =DIUF.ID_INVENTARIO_FISICO
INNER JOIN DETALLE_UBICACION_FISICA_PRODUCTO DUFP ON
DIUF.ID_DETALLE_INVENTARIO_UBICACION_FISICA =DUFP.ID_DETALLE_INVENTARIO_UBICACION_FISICA
INNER JOIN TIENDA T ON T.ID_TIENDA =IFS.ID_TIENDA
INNER JOIN UBICACION_FISICA UBF ON UBF.ID_UBICACION_FISICA =DIUF.ID_UBICACION_FISICA
INNER JOIN PRODUCTO P ON P.ID_PRODUCTO=DUFP.ID_PRODUCTO
group by IFS.ID_INVENTARIO_FISICO,T.ID_TIENDA,UBF.ID_UBICACION_FISICA,P.ID_PRODUCTO
having IFS.ID_INVENTARIO_FISICO=new.ID_INVENTARIO_FISICO
ORDER BY 4;


DECLARE EXIT HANDLER FOR err_no_more_records





BEGIN
END;

/* TIENES QUE PONER A RESTEO PARA QUE PRIMARY EMPIESE DESDE 1*/
CALL RESETEO();

OPEN c;

size: LOOP
FETCH c INTO id_deta,_ID_TIENDA,id_ubicacion,id_producto,_cant;


INSERT INTO STOCK_PRODUCTO_TIENDA_ORIGEN
(ID_PRODUCTO,ID_TIENDA_ORIGEN,CANTIDAD,ULTIMA_FECHA_INGRESO,DESCRIPCION)
VALUES
(id_producto,_ID_TIENDA,_cant, curdate(),'')
ON DUPLICATE KEY UPDATE
STOCK_PRODUCTO_TIENDA_ORIGEN.CANTIDAD = STOCK_PRODUCTO_TIENDA_ORIGEN.CANTIDAD + _cant;

/*
INSERT INTO DETALLE_ALMACEN_PRODUCTOS (ID_PRODUCTO,COSTO,ID_TIENDA,CANTIDAD,SALIERON
,QUEDARON,FECHA_INGRESO,FECHA_VENCIMIENTO,DESCRIPCION_MOTIVO,
ID_UBICACION_FISICA,ID_PROCEDENCIA_PRODUCTO_ALMACEN,ID_ESTADO_PRODUCTO_COSTO_ALMACEN)
VALUES(id_producto,0,_ID_TIENDA,_cant,0,_cant,CURDATE(),CURDATE(),'',id_ubicacion,1,1); 
*/

/* hay que registrar cada ingreso */
INSERT INTO INGRESO_PRODUCTO_TIENDA(ID_TIENDA,ID_PRODUCTO,CANTIDAD,FECHA_INGRESO,FECHA_VENCIMIENTO
,MOTIVO,ID_UBICACION_FISICA,COSTO_UNITARIO) VALUES (_ID_TIENDA,id_producto,_cant,curdate(),curdate(),'INVENTARIO SISTEMA',
id_ubicacion,0);



END LOOP size;

CLOSE c;


END//
DELIMITER ;



