INSERT INTO ESTADO_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS(NOMBRE_ESTADO, DESCRIPCION)VALUES("PRODUCTO RETORNADO","REVUELTO");

drop PROCEDURE RESETEO;


DELIMITER //
CREATE PROCEDURE RESETEO()
 BEGIN
 
DELETE FROM ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS WHERE ID_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS_COSTOS > 0;
DELETE FROM DETALLE_ALMACEN_PRODUCTOS WHERE ID_DETALLE_ALMACEN_PRODUCTOS > 0;

/*ALTER TABLE DETALLE_ALMACEN_PRODUCTOS AUTO_INCREMENT = 1;*/

DELETE FROM STOCK_PRODUCTO_TIENDA_ORIGEN WHERE ID_PRODUCTO > 0 and ID_TIENDA_ORIGEN > 0;
DELETE FROM INGRESO_PRODUCTO_TIENDA WHERE ID_INGRESO_PRODUCTO_TIENDA > 0;
DELETE FROM SALIDA_PRODUCTO_TIENDA WHERE ID_SALIDA_PRODUCTO_TIENDA > 0;


 END //
DELIMITER ;





/* HAY QUE PROBAR */


DROP TRIGGER elimina_venta_rapida;


DELIMITER //
CREATE TRIGGER elimina_venta_rapida
BEFORE DELETE ON DETALLE_VENTA_RAPIDA_PRODUCTO
 FOR EACH ROW
 BEGIN

declare x int(11) default 0;
DECLARE id_  int(11) default 0;
declare id_salida INT(50) default 0;

/*
agregado para las salidas en almacen
*/
DECLARE id_cliente  int(11) default 0;
DECLARE desc_ubicacion VARCHAR(370) default '';


DECLARE id_deta  int(50);
DECLARE _cant int(10);
DECLARE _resto int(10);
DECLARE _ID_TIENDA  INT(11);
DECLARE err_no_more_records CONDITION FOR 1329;


DECLARE c CURSOR FOR select ID_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS_COSTOS,
ID_DETALLE_ALMACEN_PRODUCTOS,
OBSERVACIONES_UBICACION,
CANTIDAD from ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS
where CODIGO_FACTURA_BOLETA=concat('VR',OLD.ID_DETALLE_VENTA_RAPIDA_PRODUCTO);

DECLARE EXIT HANDLER FOR err_no_more_records

BEGIN
END;

select distinct v.ID_TIENDA into id_ from DETALLE_VENTA_RAPIDA_PRODUCTO dt 
inner join VENTA_RAPIDA v
on dt.ID_VENTA_RAPIDA=v.ID_VENTA_RAPIDA where v.ID_VENTA_RAPIDA=OLD.ID_VENTA_RAPIDA;

UPDATE STOCK_PRODUCTO_TIENDA_ORIGEN AS stk
set stk.CANTIDAD = stk.CANTIDAD+OLD.CANTIDAD
where stk.ID_PRODUCTO = OLD.ID_PRODUCTO and stk.ID_TIENDA_ORIGEN = id_;
/*  TIENES QUE AGERGAR LAS ORDENES DE SALIDA */
/* AGREGAR EL REGISTRO DE DECREMENTO EN EL DETALLE*/


OPEN c;

size: LOOP
FETCH c INTO id_salida,id_deta,desc_ubicacion,_cant;


/* Me quede aqui !!! */


UPDATE ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS SET 
ID_ESTADO_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS =3 WHERE ID_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS_COSTOS=id_salida;

UPDATE DETALLE_ALMACEN_PRODUCTOS SET SALIERON = SALIERON - _cant 
/* SEGUN CADA DETALLE */,QUEDARON = QUEDARON + _cant, ID_ESTADO_PRODUCTO_COSTO_ALMACEN=1
WHERE ID_DETALLE_ALMACEN_PRODUCTOS=id_deta;



END LOOP size;
CLOSE c;


END//
DELIMITER ;