/**
 *
 **Copyright  2011 Yury Daniel Zavaleta De la Cruz
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and  limitations under the License.
 */

/*agregago para matxencargo*/

CREATE TABLE UBICACION_FISICA(
ID_UBICACION_FISICA int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_UBICACION_FISICA VARCHAR(100) NOT NULL DEFAULT "",
DESCRIPCION_UBICACION_FISICA VARCHAR(100) NOT NULL DEFAULT "",
PRIMARY KEY (ID_UBICACION_FISICA)
)ENGINE=InnoDB;

CREATE TABLE ZONA_CIUDAD(
ID_ZONA_CIUDAD int(11) NOT NULL AUTO_INCREMENT,
DESCRIPCION_ZONA_CIUDAD VARCHAR(150) NOT NULL default '',
FLAG_ESTADO VARCHAR(2) NOT NULL default 'SI',
PRIMARY KEY (ID_ZONA_CIUDAD)
)ENGINE=InnoDB;


CREATE TABLE MODELO_PRODUCTO(
ID_MODELO_PRODUCTO int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_MODELO_PRODUCTO VARCHAR(100) NOT NULL default '',
DESCRIPCION VARCHAR(250) NOT NULL default '',
PRIMARY KEY(ID_MODELO_PRODUCTO)
)ENGINE=InnoDB;

/*Agregado*/
CREATE TABLE MERCADO(
ID_MERCADO int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_MERCADO VARCHAR(200) NOT NULL default '',
DESCRIPCION VARCHAR(250) NOT NULL default '',
PRIMARY KEY(ID_MERCADO)
)ENGINE=InnoDB;

/*
Agregado
*/
CREATE TABLE ESTADO_PRODUCTO_COSTO_ALMACEN(
ID_ESTADO_PRODUCTO_COSTO_ALMACEN  int(3) NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(100) NOT NULL default '',
DESCRIPCION VARCHAR(170) NOT NULL default '',
PRIMARY KEY (ID_ESTADO_PRODUCTO_COSTO_ALMACEN)
)ENGINE=InnoDB;

/*
Agregado
*/
CREATE TABLE PROCEDENCIA_PRODUCTO_ALMACEN(
ID_PROCEDENCIA_PRODUCTO_ALMACEN  int(11) NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(100) NOT NULL default '',
DESCRIPCION VARCHAR(170) NOT NULL default '',
PRIMARY KEY (ID_PROCEDENCIA_PRODUCTO_ALMACEN)
)ENGINE=InnoDB;


/*
Agregado
*/
CREATE TABLE ESTADO_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS(
ID_ESTADO_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS  int(3) NOT NULL AUTO_INCREMENT,
NOMBRE_ESTADO VARCHAR(100) NOT NULL default '',
DESCRIPCION VARCHAR(170) NOT NULL default '',
PRIMARY KEY (ID_ESTADO_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS)
)ENGINE=InnoDB;



/*
Agregado
*/
CREATE TABLE ESTADO_IGV(
ID_ESTADO_IGV  int(3) NOT NULL AUTO_INCREMENT,
NOMBRE_ESTADO VARCHAR(100) NOT NULL default '',
DESCRIPCION VARCHAR(170) NOT NULL default '',
PRIMARY KEY (ID_ESTADO_IGV)
)ENGINE=InnoDB;


/*Agregado*/
CREATE TABLE TIPO_CLIENTE(
ID_TIPO_CLIENTE int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_TIPO_CLIENTE VARCHAR(100) NOT NULL default '',
DESCRIPCION VARCHAR(250) NOT NULL default '',
PRIMARY KEY (ID_TIPO_CLIENTE)
)ENGINE=InnoDB;

/*Agregado*/
CREATE TABLE CLIENTE(
ID_CLIENTE int(11) NOT NULL AUTO_INCREMENT,
ID_MERCADO int(11) NOT NULL,
ID_TIPO_CLIENTE int(11) NOT NULL,
NOMBRE_CLIENTE VARCHAR(150) NOT NULL default '',
RAZON_SOCIAL VARCHAR(150) NOT NULL default '',
GIRO_RUBRO VARCHAR(150) NOT NULL default '',
CONTACTO VARCHAR(100) NOT NULL default '',
RUC_CLIENTE VARCHAR(40) NOT NULL default '',
DIRECCION VARCHAR(250) NOT NULL default '',
TELEFONO VARCHAR(25) NOT NULL DEFAULT '',
CELULAR VARCHAR(25) NOT NULL DEFAULT '',
NEXTEL VARCHAR(25) NOT NULL DEFAULT '',
CORREO VARCHAR(250) NOT NULL DEFAULT '',
ID_ZONA_CIUDAD int(11) NOT NULL,
PRIMARY KEY(ID_CLIENTE),
FOREIGN KEY (ID_MERCADO) REFERENCES MERCADO (ID_MERCADO),
FOREIGN KEY (ID_TIPO_CLIENTE) REFERENCES TIPO_CLIENTE (ID_TIPO_CLIENTE),
FOREIGN KEY (ID_ZONA_CIUDAD) REFERENCES ZONA_CIUDAD (ID_ZONA_CIUDAD)
)ENGINE=InnoDB;


CREATE TABLE COLOR_PRODUCTO(
ID_COLOR_PRODUCTO int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_COLOR_PRODUCTO VARCHAR(100) NOT NULL default '',
DESCRIPCION VARCHAR(170) NOT NULL default '',
PRIMARY KEY(ID_COLOR_PRODUCTO)
)ENGINE=InnoDB;

CREATE TABLE TALLA_PRODUCTO(
ID_TALLA_PRODUCTO int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_TALLA_PRODUCTO VARCHAR(100) NOT NULL default '',
DESCRIPCION VARCHAR(170) NOT NULL default '',
PRIMARY KEY(ID_TALLA_PRODUCTO)
)ENGINE=InnoDB;

CREATE TABLE ESTADO_PRODUCTO(
ID_ESTADO_PRODUCTO int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_ESTADO_PRODUCTO VARCHAR(100) NOT NULL default '',
DESCRIPCION VARCHAR(170) NOT NULL default '',
PRIMARY KEY(ID_ESTADO_PRODUCTO)
)ENGINE=InnoDB;

CREATE TABLE MATERIAL_PRODUCTO(
ID_MATERIAL_PRODUCTO int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_MATERIAL_PRODUCTO VARCHAR(100) NOT NULL default '',
DESCRIPCION VARCHAR(170) NOT NULL default '',
PRIMARY KEY(ID_MATERIAL_PRODUCTO)
)ENGINE=InnoDB;



CREATE TABLE TIPO_PRODUCTO(
ID_TIPO_PRODUCTO int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_TIPO_PRODUCTO VARCHAR(100) NOT NULL default '',
DESCRIPCION VARCHAR(170) NOT NULL default '',
PRIMARY KEY (ID_TIPO_PRODUCTO)
)ENGINE=InnoDB;

CREATE TABLE TIPO_VENTA(
ID_TIPO_VENTA  int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_TIPO_VENTA VARCHAR(100) NOT NULL default '',
DESCRIPCION VARCHAR(170) NOT NULL default '',
PRIMARY KEY (ID_TIPO_VENTA)
)ENGINE=InnoDB;

CREATE TABLE ESTADO_VENTA(
ID_ESTADO_VENTA  int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_TESTADO_VENTA VARCHAR(100) NOT NULL default '',
DESCRIPCION VARCHAR(170) NOT NULL default '',
PRIMARY KEY (ID_ESTADO_VENTA)
)ENGINE=InnoDB;


CREATE TABLE TIPO_EMPLEADO(
ID_TIPO_EMPLEADO int(11) NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(100) NOT NULL default '',
DESCRIPCION VARCHAR(170) NOT NULL default '',
PRIMARY KEY (ID_TIPO_EMPLEADO)
)ENGINE=InnoDB;


CREATE TABLE EMPLEADO(
ID_EMPLEADO  int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_EMPLEADO VARCHAR(150) NOT NULL default '',
DIRECCION VARCHAR(250) NOT NULL default '',
TELEFONO VARCHAR(48)NOT NULL DEFAULT '',
CORREO VARCHAR(68) NOT NULL DEFAULT '',
USUARIO VARCHAR(100) NOT NULL DEFAULT '',
PASSWORD VARCHAR(170) NOT NULL DEFAULT '',
ID_TIPO_EMPLEADO int(11) NOT NULL,
PRIMARY KEY (ID_EMPLEADO),
FOREIGN KEY (ID_TIPO_EMPLEADO) REFERENCES TIPO_EMPLEADO (ID_TIPO_EMPLEADO)
)ENGINE=InnoDB;


CREATE TABLE NEGOCIO(
ID_NEGOCIO int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_NEGOCIO VARCHAR(350) NOT NULL default '',
PRIMARY KEY (ID_NEGOCIO)
)ENGINE=InnoDB;


CREATE TABLE TIENDA(
ID_TIENDA int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_TIENDA VARCHAR(350) NOT NULL default '',
DIRECCION VARCHAR(200) NOT NULL default '',
CIUDAD VARCHAR(200) NOT NULL default '',
DISTRITO VARCHAR(200) NOT NULL default '',
TELEFONOS VARCHAR(400) NOT NULL default '',
NUMERO_RUC VARCHAR(20) NOT NULL default '',
ID_NEGOCIO int(11) ,
PRIMARY KEY (ID_TIENDA),
FOREIGN KEY (ID_NEGOCIO) REFERENCES NEGOCIO (ID_NEGOCIO)
)ENGINE=InnoDB;



CREATE TABLE VENTA(
ID_VENTA int(11) NOT NULL AUTO_INCREMENT,
BLOQUE_VENTA INT(4) NOT NULL,
NUMERO_VENTA INT(6) NOT NULL,
FECHA_VENTA DATE NOT NULL,
/*Agregado*/
FECHA_VENTA_EMISION DATE NOT NULL,
ID_TIENDA INT(11) NOT NULL,
ID_EMPLEADO INT(11) NOT NULL,
ID_TIPO_VENTA  INT(11) NOT NULL,
ID_ESTADO_VENTA  int(11) ,
TOTAL_VENTA DECIMAL(9,2) NOT NULL DEFAULT 0,
OBSERVACIONES VARCHAR(200) NOT NULL DEFAULT '',
/*Agregado*/
ID_CLIENTE INT(11) NOT NULL,
TOTAL_PAGOS_CREDITO DECIMAL(9,2) NOT NULL DEFAULT 0,
/*CAMBIO TABLA*/
FACTURA_RELACIONADA VARCHAR(50)  DEFAULT '',
PRIMARY KEY (ID_VENTA),
FOREIGN KEY (ID_TIENDA) REFERENCES TIENDA (ID_TIENDA),
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO),
FOREIGN KEY (ID_TIPO_VENTA) REFERENCES TIPO_VENTA (ID_TIPO_VENTA),
/*Agregado*/
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
FOREIGN KEY (ID_ESTADO_VENTA) REFERENCES ESTADO_VENTA (ID_ESTADO_VENTA)
)ENGINE=InnoDB;




/*AGREGANDO LAS FACTURAS DE VENTA*/

CREATE TABLE MOTIVO_TRANSLADO_FACTURA(
ID_MOTIVO_TRANSLADO_FACTURA int(11) NOT NULL AUTO_INCREMENT,
MOTIVO VARCHAR(100) NOT NULL default '',
DESCRIPCION VARCHAR(250) NOT NULL default '',
PRIMARY KEY(ID_MOTIVO_TRANSLADO_FACTURA)
)ENGINE=InnoDB;

CREATE TABLE IGV_FACTURA(
ID_IGV_FACTURA int(11) NOT NULL AUTO_INCREMENT,
MONTO DECIMAL(4,2) NOT NULL,
DESCRIPCION VARCHAR(250) NOT NULL default '',
ID_ESTADO_IGV int (3) not null,
PRIMARY KEY(ID_IGV_FACTURA),
FOREIGN KEY (ID_ESTADO_IGV) REFERENCES ESTADO_IGV (ID_ESTADO_IGV)
)ENGINE=InnoDB;


CREATE TABLE UNIDAD_TRANSPORTE(
ID_UNIDAD_TRANSPORTE int(11) NOT NULL AUTO_INCREMENT,
MARCA VARCHAR(200) NOT NULL DEFAULT '',
NUMERO_PLACA VARCHAR(200) NOT NULL DEFAULT '',
NUMERO_CONSTANCIA_INSCRIPCION VARCHAR(200) NOT NULL DEFAULT '',
OBSERVACIONES VARCHAR(200) NOT NULL DEFAULT '',
FECHA_REGISTRO DATE NOT NULL,
PRIMARY KEY (ID_UNIDAD_TRANSPORTE)
)ENGINE=InnoDB;

CREATE TABLE CONDUCTOR(
ID_CONDUCTOR INT(11) NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(200) NOT NULL DEFAULT '',
RUC VARCHAR(200) NOT NULL DEFAULT '',
NUMERO_LICENCIA_CONDUCIR VARCHAR(200) NOT NULL DEFAULT '',
OBSERVACIONES VARCHAR(200) NOT NULL DEFAULT '',
FECHA_REGISTRO DATE NOT NULL,
PRIMARY KEY (ID_CONDUCTOR)
)ENGINE=InnoDB;






CREATE TABLE FACTURA_VENTA(
ID_FACTURA_VENTA int(12) NOT NULL AUTO_INCREMENT,
/* El Bloque y el Numero Sale con MOD en Mysql*/
BLOQUE_FACTURA INT(4) NOT NULL,
NUMERO_FACTURA INT(6) NOT NULL,
FECHA_VENTA DATE NOT NULL,
/*Agregado*/
FECHA_VENTA_EMISION DATETIME NOT NULL,
ID_TIENDA INT(11) NOT NULL,
ID_EMPLEADO INT(11) NOT NULL,
ID_TIPO_VENTA  INT(11) NOT NULL,
ID_ESTADO_VENTA  int(11) ,
TOTAL_VENTA DECIMAL(9,2) NOT NULL DEFAULT 0,
ID_IGV_FACTURA int(11) NOT NULL,
TOTAL_VENTA_INCLUIDO_IGV DECIMAL(11,2) NOT NULL DEFAULT 0,
OBSERVACIONES VARCHAR(200) NOT NULL DEFAULT '',
/*Agregado*/
ID_CLIENTE INT(11) NOT NULL,
TOTAL_PAGOS_CREDITO DECIMAL(9,2) NOT NULL DEFAULT 0,
PRIMARY KEY (ID_FACTURA_VENTA),
FOREIGN KEY (ID_TIENDA) REFERENCES TIENDA (ID_TIENDA),
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO),
FOREIGN KEY (ID_TIPO_VENTA) REFERENCES TIPO_VENTA (ID_TIPO_VENTA),
/*Agregado*/
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
FOREIGN KEY (ID_ESTADO_VENTA) REFERENCES ESTADO_VENTA (ID_ESTADO_VENTA),
FOREIGN KEY (ID_IGV_FACTURA) REFERENCES IGV_FACTURA (ID_IGV_FACTURA)
)ENGINE=InnoDB;

CREATE TABLE GUIA_REMICION(
ID_GUIA_REMICION INT(11) NOT NULL AUTO_INCREMENT,
PUNTO_PARTIDA VARCHAR(200) NOT NULL DEFAULT '',
PUNTO_LLEGADA VARCHAR(200) NOT NULL DEFAULT '',
OBSERVACIONES VARCHAR(200) NOT NULL DEFAULT '',
FECHA_INICIO_TRANSLADO DATE NOT NULL,
ID_UNIDAD_TRANSPORTE INT(11) NOT NULL,
ID_CONDUCTOR INT(11) NOT NULL,
ID_MOTIVO_TRANSLADO_FACTURA INT(11) NOT NULL,
ID_FACTURA_VENTA int(12) NOT NULL,
PRIMARY KEY (ID_GUIA_REMICION),
FOREIGN KEY (ID_UNIDAD_TRANSPORTE) REFERENCES UNIDAD_TRANSPORTE (ID_UNIDAD_TRANSPORTE),
FOREIGN KEY (ID_CONDUCTOR) REFERENCES CONDUCTOR (ID_CONDUCTOR),
FOREIGN KEY (ID_MOTIVO_TRANSLADO_FACTURA) REFERENCES MOTIVO_TRANSLADO_FACTURA (ID_MOTIVO_TRANSLADO_FACTURA),
FOREIGN KEY (ID_FACTURA_VENTA) REFERENCES FACTURA_VENTA (ID_FACTURA_VENTA)
)ENGINE=InnoDB;



CREATE TABLE PRODUCTO(
ID_PRODUCTO int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_PRODUCTO VARCHAR(300) NOT NULL DEFAULT '',
ID_MODELO_PRODUCTO  INT(11) NOT NULL,
ID_COLOR_PRODUCTO INT(11) NOT NULL,
ID_TALLA_PRODUCTO INT(11) NOT NULL,
FECHA_INGRESO DATE NOT NULL,
ID_ESTADO_PRODUCTO INT(11) NOT NULL,
ID_TIPO_PRODUCTO  INT(11) NOT NULL,
ID_MATERIAL_PRODUCTO INT(11) NOT NULL,
PRIMARY KEY (ID_PRODUCTO), 
FOREIGN KEY (ID_MODELO_PRODUCTO) REFERENCES MODELO_PRODUCTO (ID_MODELO_PRODUCTO),
FOREIGN KEY (ID_TIPO_PRODUCTO)  REFERENCES TIPO_PRODUCTO (ID_TIPO_PRODUCTO),
FOREIGN KEY (ID_COLOR_PRODUCTO) REFERENCES COLOR_PRODUCTO (ID_COLOR_PRODUCTO),
FOREIGN KEY (ID_TALLA_PRODUCTO) REFERENCES TALLA_PRODUCTO (ID_TALLA_PRODUCTO),
FOREIGN KEY (ID_ESTADO_PRODUCTO) REFERENCES ESTADO_PRODUCTO (ID_ESTADO_PRODUCTO),
FOREIGN KEY (ID_TIPO_PRODUCTO) REFERENCES TIPO_PRODUCTO (ID_TIPO_PRODUCTO),
FOREIGN KEY (ID_MATERIAL_PRODUCTO) REFERENCES MATERIAL_PRODUCTO (ID_MATERIAL_PRODUCTO)
)ENGINE=InnoDB;

CREATE TABLE DETALLE_VENTA_PRODUCTO(
ID_VENTA INT(11) NOT NULL,
ID_PRODUCTO INT(11) NOT NULL,
CANTIDAD INT NOT NULL DEFAULT 1,
PRECIO_VENTA DECIMAL (9,2) NOT NULL,
DESCUENTO DECIMAL (9,2) NOT NULL DEFAULT 0.0,
SUB_TOTAL DECIMAL (9,2) NOT NULL, 
PRIMARY KEY (ID_VENTA,ID_PRODUCTO),
FOREIGN KEY (ID_VENTA)
REFERENCES VENTA (ID_VENTA),
FOREIGN KEY (ID_PRODUCTO)
REFERENCES PRODUCTO (ID_PRODUCTO)
)ENGINE=InnoDB;


CREATE TABLE DETALLE_FACTURA_VENTA_PRODUCTO(
ID_FACTURA_VENTA INT(11) NOT NULL,
ID_PRODUCTO INT(11) NOT NULL,
CANTIDAD INT NOT NULL DEFAULT 1,
PRECIO_VENTA DECIMAL (9,2) NOT NULL,
DESCUENTO DECIMAL (9,2) NOT NULL DEFAULT 0.0,
SUB_TOTAL DECIMAL (9,2) NOT NULL, 
PRIMARY KEY (ID_FACTURA_VENTA,ID_PRODUCTO),
FOREIGN KEY (ID_FACTURA_VENTA)
REFERENCES FACTURA_VENTA (ID_FACTURA_VENTA),
FOREIGN KEY (ID_PRODUCTO)
REFERENCES PRODUCTO (ID_PRODUCTO)
)ENGINE=InnoDB;



CREATE TABLE DEVOLUCION_LIMA(
ID_DEVOLUCION int(11) NOT NULL AUTO_INCREMENT,
ID_PRODUCTO INT(11) NOT NULL,
FECHA_DEVOLUCION DATE NOT NULL,
MOTIVO_DEVOLUCION VARCHAR(300) NOT NULL DEFAULT '',
PRIMARY KEY (ID_DEVOLUCION),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
)ENGINE=InnoDB;

CREATE TABLE CAMBIO(
ID_CAMBIO int(11) NOT NULL AUTO_INCREMENT,
ID_VENTA INT(11) NOT NULL,
FECHA_CAMBIO DATE NOT NULL,
MOTIVO_CAMBIO VARCHAR(300) NOT NULL DEFAULT '',
PRIMARY KEY (ID_CAMBIO),
FOREIGN KEY (ID_VENTA)REFERENCES VENTA (ID_VENTA)
)ENGINE=InnoDB;

CREATE TABLE DETALLE_CAMBIO_PRODUCTO(
ID_CAMBIO INT(11) NOT NULL,
ID_PRODUCTO_CAMBIO INT(11) NOT NULL,
ID_PRODUCTO_CAMBIADA INT(11) NOT NULL,
PRIMARY KEY (ID_CAMBIO,ID_PRODUCTO_CAMBIO,ID_PRODUCTO_CAMBIADA),
FOREIGN KEY (ID_CAMBIO) REFERENCES CAMBIO (ID_CAMBIO),
FOREIGN KEY (ID_PRODUCTO_CAMBIO) REFERENCES PRODUCTO (ID_PRODUCTO),
FOREIGN KEY (ID_PRODUCTO_CAMBIADA) REFERENCES PRODUCTO (ID_PRODUCTO)
)ENGINE=InnoDB;

CREATE TABLE STOCK_PRODUCTO_TIENDA_ORIGEN(
ID_PRODUCTO INT(11) NOT NULL,
ID_TIENDA_ORIGEN  INT(11) NOT NULL,
CANTIDAD INT(5) NOT NULL,
ULTIMA_FECHA_INGRESO DATE NOT NULL,
DESCRIPCION VARCHAR(370) DEFAULT '',
CANTIDAD_MINIMA_STOCK INT NOT NULL default 1,
PRIMARY KEY (ID_PRODUCTO,ID_TIENDA_ORIGEN),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
FOREIGN KEY (ID_TIENDA_ORIGEN) REFERENCES TIENDA (ID_TIENDA)
)ENGINE=InnoDB;


/* VAMOS A AGREGAR LA UBICACION DEL PRODUCTO*/
/*   AQUI ES EN DONDE SE REGISTRAN LOS INGRESOS */
CREATE TABLE INGRESO_PRODUCTO_TIENDA(
ID_INGRESO_PRODUCTO_TIENDA INT(11) NOT NULL AUTO_INCREMENT,
ID_TIENDA INT(11) NOT NULL,
ID_PRODUCTO INT(11) NOT NULL,
CANTIDAD  INT(11) NOT NULL,
FECHA_INGRESO DATE NOT NULL,
FECHA_VENCIMIENTO DATE NOT NULL DEFAULT '1990-01-01',
MOTIVO VARCHAR(300) NOT NULL DEFAULT '',
/*UBICACION VARCHAR(300) NOT NULL DEFAULT '',*/
ID_UBICACION_FISICA int(11) NOT NULL,
COSTO_UNITARIO DECIMAL (9,2) NOT NULL,
PRIMARY KEY (ID_INGRESO_PRODUCTO_TIENDA),
FOREIGN KEY (ID_TIENDA) REFERENCES TIENDA (ID_TIENDA),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
FOREIGN KEY (ID_UBICACION_FISICA) REFERENCES UBICACION_FISICA (ID_UBICACION_FISICA)
)ENGINE=InnoDB;


CREATE TABLE SALIDA_PRODUCTO_TIENDA(
ID_SALIDA_PRODUCTO_TIENDA INT(11) NOT NULL AUTO_INCREMENT,
ID_TIENDA INT(11) NOT NULL,
ID_PRODUCTO INT(11) NOT NULL,
CANTIDAD  INT(11) NOT NULL,
FECHA_SALIDA DATE NOT NULL,
MOTIVO VARCHAR(300) NOT NULL DEFAULT '',
PRIMARY KEY (ID_SALIDA_PRODUCTO_TIENDA),
FOREIGN KEY (ID_TIENDA) REFERENCES TIENDA (ID_TIENDA),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
)ENGINE=InnoDB;


CREATE TABLE PRESTAMO_PRODUCTO_TIENDA_USUARIO(
ID_PRESTAMO_PRODUCTO_TIENDA int(11) NOT NULL AUTO_INCREMENT,
ID_TIENDA_PRESTA int(11) NOT NULL,
ID_TIENDA_RECIBE INT(11) NOT NULL,
ID_EMPLEADO INT(11) not null,
CANTIDAD  INT(11) NOT NULL,
FECHA_INGRESO DATE NOT NULL,
PRIMARY KEY (ID_PRESTAMO_PRODUCTO_TIENDA),
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO),
FOREIGN KEY (ID_TIENDA_PRESTA) REFERENCES TIENDA (ID_TIENDA),
FOREIGN KEY (ID_TIENDA_RECIBE) REFERENCES TIENDA (ID_TIENDA)
)ENGINE=InnoDB;



/*Agregado*/
  CREATE TABLE ESTADO_ORDEN_COMPRA(
 ID_ESTADO_ORDEN_COMPRA INT(11) auto_increment not null,
 NOMBRE VARCHAR(250) not null default '',
 DESCRIPCION VARCHAR(100) not null default '',
 PRIMARY KEY (ID_ESTADO_ORDEN_COMPRA)
 )ENGINE=InnoDB;

/*Agregado*/
  CREATE TABLE ESTADO_FACTURACION_ORDEN_COMPRA(
 ID_ESTADO_FACTURACION_ORDEN_COMPRA INT(11) auto_increment not null,
 NOMBRE VARCHAR(250) not null default '',
 DESCRIPCION VARCHAR(100) not null default '',
 PRIMARY KEY (ID_ESTADO_FACTURACION_ORDEN_COMPRA)
 )ENGINE=InnoDB;

/*Agregado*/
 CREATE TABLE TIPO_PROVEEDOR(
 ID_TIPO_PROVEEDOR INT(11) auto_increment not null,
 NOMBRE VARCHAR(250) not null default '',
 DESCRIPCION VARCHAR(100) not null default '',
 PRIMARY KEY (ID_TIPO_PROVEEDOR)
 )ENGINE=InnoDB;

/*Agregado*/
 CREATE TABLE PROVEEDOR(
 ID_PROVEEDOR INT(11) auto_increment not null,
 NOMBRE varchar(170) not null default '',
 DIRECCION VARCHAR(150) not null default '',
 ID_TIPO_PROVEEDOR INT(11), 
 TELEFONO VARCHAR(48)NOT NULL DEFAULT '',
 CELULAR VARCHAR(48)NOT NULL DEFAULT '',
 NEXTEL VARCHAR(48)NOT NULL DEFAULT '',
 CORREO VARCHAR(68) NOT NULL DEFAULT '',
 PRIMARY KEY (ID_PROVEEDOR),
  FOREIGN KEY (ID_TIPO_PROVEEDOR) REFERENCES TIPO_PROVEEDOR (ID_TIPO_PROVEEDOR)
 )ENGINE=InnoDB;


/*Agregado*/
CREATE TABLE ORDEN_COMPRA(
ID_ORDEN_COMPRA int(11) NOT NULL auto_increment,
FECHA_CREACION_ORDEN_COMPRA DATE NOT NULL,
FECHA_ENTREGA_ORDEN_COMPRA DATE NOT NULL,
ID_PROVEEDOR INT(11),
TOTAL_ORDEN_COMPRA decimal(9,2) not null default 0.0,
TOTAL_PAGOS_CREDITO_ORDEN_COMPRA decimal(9,2) not null default 0.0,
ID_ESTADO_ORDEN_COMPRA INT(1) NOT NULL DEFAULT 1,
ID_ESTADO_FACTURACION_ORDEN_COMPRA INT(1) NOT NULL DEFAULT 1,
OBSERVACIONES VARCHAR(300) NOT NULL DEFAULT '',
 PRIMARY KEY (ID_ORDEN_COMPRA),
 FOREIGN KEY (ID_ESTADO_ORDEN_COMPRA) REFERENCES ESTADO_ORDEN_COMPRA (ID_ESTADO_ORDEN_COMPRA),
FOREIGN KEY (ID_ESTADO_FACTURACION_ORDEN_COMPRA) REFERENCES ESTADO_FACTURACION_ORDEN_COMPRA (ID_ESTADO_FACTURACION_ORDEN_COMPRA),
FOREIGN KEY (ID_PROVEEDOR ) REFERENCES PROVEEDOR (ID_PROVEEDOR )
)ENGINE=InnoDB;	

/*Agregado*/
CREATE TABLE DETALLE_ORDEN_COMPRA_PRODUCTO(
ID_ORDEN_COMPRA INT(11) NOT NULL,
ID_PRODUCTO INT(11) NOT NULL,
CANTIDAD INT NOT NULL DEFAULT 1,
PRECIO_VENTA DECIMAL (9,2) NOT NULL,
DESCUENTO DECIMAL (4,2) NOT NULL DEFAULT 0.0,
SUB_TOTAL DECIMAL (9,2) NOT NULL, 
PRIMARY KEY (ID_ORDEN_COMPRA,ID_PRODUCTO),
FOREIGN KEY (ID_ORDEN_COMPRA)
REFERENCES ORDEN_COMPRA (ID_ORDEN_COMPRA),
FOREIGN KEY (ID_PRODUCTO)
REFERENCES PRODUCTO (ID_PRODUCTO)
)ENGINE=InnoDB;


/*Agregado*/
CREATE TABLE FACTURA_COMPRA(
ID_FACTURA_COMPRA int(11) NOT NULL auto_increment,
ID_ORDEN_COMPRA int NOT NULL default 0,
FECHA_RECEPCION DATE not NULL ,
NUMERO_FACTURA_COMPRA VARCHAR(68) Not NULL default '',
NUMERO_GUIA_REMISION  VARCHAR(68) Not NULL default '',
DESCRIPCION  varchar(170) Not NULL default '',
ID_EMPLEADO  int(11),
PRIMARY KEY (ID_FACTURA_COMPRA),
FOREIGN KEY (ID_ORDEN_COMPRA) REFERENCES ORDEN_COMPRA (ID_ORDEN_COMPRA),
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO)
)ENGINE=InnoDB;

/*Agregado*/
CREATE TABLE PRECIO_PRODUCTO(
ID_PRODUCTO INT(11),
FECHA_ACTUALIZACION DATE NOT NULL,
PRECIO_PRODUCTO DECIMAL(9,2) NOT NULL DEFAULT 0,
PRIMARY KEY (ID_PRODUCTO),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
)ENGINE=InnoDB;



/*Agregado*/
CREATE TABLE INGRESOS_ECONOMICOS(
ID_INGRESOS_ECONOMICOS int(11) NOT NULL AUTO_INCREMENT,
MOTIVO VARCHAR(200) NOT NULL default '',
NOTA VARCHAR(300) NOT NULL default '',
FECHA_CREACION DATE not NULL ,
TOTAL DECIMAL (9,2) NOT NULL,
PRIMARY KEY(ID_INGRESOS_ECONOMICOS)
)ENGINE=InnoDB;
/*Agregado*/
CREATE TABLE GASTOS_ECONOMICOS(
ID_GASTOS_ECONOMICOS int(11) NOT NULL AUTO_INCREMENT,
MOTIVO VARCHAR(200) NOT NULL default '',
NOTA VARCHAR(300) NOT NULL default '',
FECHA_CREACION DATE not NULL ,
TOTAL DECIMAL (9,2) NOT NULL,
PRIMARY KEY(ID_GASTOS_ECONOMICOS)
)ENGINE=InnoDB;

/*Agregado*/
CREATE TABLE PAGO_VENTA_CREDITO(
ID_PAGO_VENTA_CREDITO int(11) NOT NULL AUTO_INCREMENT,
ID_VENTA INT(11) ,
FECHA_INGRESO DATE NOT NULL,
ID_EMPLEADO INT(11) ,
OBSERVACIONES VARCHAR(170) NOT NULL default '',
CANTIDAD  DECIMAL (9,2) NOT NULL,
PRIMARY KEY (ID_PAGO_VENTA_CREDITO),
FOREIGN KEY (ID_VENTA) REFERENCES VENTA (ID_VENTA),
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO)
)ENGINE=InnoDB;


/*Agregado*/
CREATE TABLE PAGO_FACTURA_VENTA_CREDITO(
ID_PAGO_FACTURA_VENTA_CREDITO int(11) NOT NULL AUTO_INCREMENT,
ID_FACTURA_VENTA INT(12) ,
FECHA_INGRESO DATE NOT NULL,
ID_EMPLEADO INT(11) ,
OBSERVACIONES VARCHAR(170) NOT NULL default '',
CANTIDAD  DECIMAL (9,2) NOT NULL,
PRIMARY KEY (ID_PAGO_FACTURA_VENTA_CREDITO),
FOREIGN KEY (ID_FACTURA_VENTA) REFERENCES FACTURA_VENTA (ID_FACTURA_VENTA),
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO)
)ENGINE=InnoDB;




/*Agregado*/
CREATE TABLE PAGO_COMPRA_CREDITO(
ID_PAGO_COMPRA_CREDITO int(11) NOT NULL AUTO_INCREMENT,
ID_ORDEN_COMPRA INT(11) ,
FECHA_INGRESO DATE NOT NULL,
ID_EMPLEADO INT(11) not null,
OBSERVACIONES VARCHAR(170) NOT NULL default '',
CANTIDAD  DECIMAL (9,2) NOT NULL,
PRIMARY KEY (ID_PAGO_COMPRA_CREDITO),
FOREIGN KEY (ID_ORDEN_COMPRA) REFERENCES ORDEN_COMPRA (ID_ORDEN_COMPRA),
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO)
)ENGINE=InnoDB;

/*Agregado*/
create table NOTA_CREDITO(
ID_NOTA_CREDITO INT(11) NOT NULL AUTO_INCREMENT,
FECHA_REGISTRO DATE NOT NULL,
CANTIDAD decimal (9,3) not null,
DESCRIPCION varchar(200),
ID_VENTA INT(11),
PRIMARY KEY (ID_NOTA_CREDITO),
FOREIGN KEY (ID_VENTA) REFERENCES VENTA (ID_VENTA)
)ENGINE=InnoDB;







DELIMITER //
CREATE TRIGGER inserta_detalles
 AFTER INSERT ON DETALLE_VENTA_PRODUCTO
/*
usa este detalle, para que uses el ID_VENTA, a traves de eso vas a poder actualizar un campo
en la venta que se llame : Utilidad y que sea la resta del costo en almacen entre el precio de venta
*/
 FOR EACH ROW
 BEGIN
declare x int(11) default 0;
declare id_ int(11) default 0;

/*
agregado para las salidas en almacen
*/
DECLARE id_cliente  int(11) default 0;
DECLARE desc_ubicacion VARCHAR(370) default '';


DECLARE id_deta  int(50);
DECLARE _cant int(10);
DECLARE _resto int(10);
DECLARE _ID_TIENDA  INT(11);
DECLARE err_no_more_records CONDITION FOR 1329;
DECLARE c CURSOR FOR select dt.ID_DETALLE_ALMACEN_PRODUCTOS, dt.QUEDARON,dt.ID_TIENDA
,UF.NOMBRE_UBICACION_FISICA from DETALLE_ALMACEN_PRODUCTOS dt 
inner join UBICACION_FISICA UF on UF.ID_UBICACION_FISICA = dt.ID_UBICACION_FISICA
where dt.ID_PRODUCTO=new.ID_PRODUCTO and dt.ID_ESTADO_PRODUCTO_COSTO_ALMACEN=1

order by dt.COSTO;
DECLARE EXIT HANDLER FOR err_no_more_records



BEGIN
END;


/*agregado un nuevo into para cliente.*/
/*select ID_CLIENTE into id_cliente from VENTA where ID_VENTA = NEW.ID_VENTA;   */

select distinct v.ID_TIENDA, v.ID_CLIENTE into id_ , id_cliente  from DETALLE_VENTA_PRODUCTO dt inner join VENTA v
on dt.ID_VENTA=v.ID_VENTA where v.ID_VENTA=NEW.ID_VENTA;
UPDATE STOCK_PRODUCTO_TIENDA_ORIGEN AS stk
set stk.CANTIDAD = stk.CANTIDAD-NEW.CANTIDAD
where stk.ID_PRODUCTO = new.ID_PRODUCTO and stk.ID_TIENDA_ORIGEN = id_;
set _resto =new.CANTIDAD;
OPEN c;

SET x = 0;
size: LOOP
FETCH c INTO id_deta,_cant,_ID_TIENDA,desc_ubicacion;

if id_  = _ID_TIENDA and _cant <= _resto then



update DETALLE_ALMACEN_PRODUCTOS set ID_ESTADO_PRODUCTO_COSTO_ALMACEN=2,SALIERON=SALIERON+_cant,QUEDARON=0  
WHERE ID_DETALLE_ALMACEN_PRODUCTOS=id_deta;
/*
agregando la referencia a orden de salida en almacen
*/
insert ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS(ID_DETALLE_ALMACEN_PRODUCTOS,ID_CLIENTE,OBSERVACIONES_UBICACION,
FECHA_REGISTRO,CODIGO_FACTURA_BOLETA,CANTIDAD,ID_ESTADO_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS)
values (id_deta,id_cliente,desc_ubicacion, NOW(),NEW.ID_VENTA,_cant,1);


set _resto = _resto - _cant;
else

if id_  = _ID_TIENDA then
update DETALLE_ALMACEN_PRODUCTOS set ID_ESTADO_PRODUCTO_COSTO_ALMACEN=1,SALIERON=SALIERON + _resto,QUEDARON=QUEDARON-_resto
WHERE ID_DETALLE_ALMACEN_PRODUCTOS=id_deta;
/*
agregando la referencia a orden de salida en almacen
*/
insert ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS(ID_DETALLE_ALMACEN_PRODUCTOS,ID_CLIENTE,OBSERVACIONES_UBICACION,
FECHA_REGISTRO,CODIGO_FACTURA_BOLETA,CANTIDAD,ID_ESTADO_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS)
values (id_deta,id_cliente,desc_ubicacion,NOW(),NEW.ID_VENTA,_resto,1);

set _resto=0;
end if;


end if;


  if _resto=0 then
 leave size; 
           
end if;

END LOOP size;
CLOSE c;


END//
DELIMITER ;

















/*
DELIMITER //
CREATE TRIGGER inserta_detalles
 AFTER INSERT ON DETALLE_VENTA_PRODUCTO
 FOR EACH ROW
 BEGIN
declare id_ int(11) default 0;
select distinct v.ID_TIENDA into id_ from DETALLE_VENTA_PRODUCTO dt inner join VENTA v
on dt.ID_VENTA=v.ID_VENTA where v.ID_VENTA=NEW.ID_VENTA;
UPDATE STOCK_PRODUCTO_TIENDA_ORIGEN AS stk
set stk.CANTIDAD = stk.CANTIDAD-NEW.CANTIDAD
where stk.ID_PRODUCTO = new.ID_PRODUCTO and stk.ID_TIENDA_ORIGEN = id_;






END//
DELIMITER ;
*/

/*
DELIMITER //
CREATE TRIGGER inserta_detalles
 AFTER INSERT ON DETALLE_VENTA_PRODUCTO
 FOR EACH ROW
 BEGIN
declare x int(11) default 0;
declare id_ int(11) default 0;
DECLARE id_deta  int(50);
DECLARE err_no_more_records CONDITION FOR 1329;
DECLARE c CURSOR FOR select dt.ID_DETALLE_ALMACEN_PRODUCTOS_COSTOS from DETALLE_ALMACEN_PRODUCTOS_COSTOS dt 
where dt.ID_PRODUCTO=new.ID_PRODUCTO and dt.ID_ESTADO_PRODUCTO_COSTO_ALMACEN=1
order by dt.COSTO;
DECLARE EXIT HANDLER FOR err_no_more_records



BEGIN
END;

select distinct v.ID_TIENDA into id_ from DETALLE_VENTA_PRODUCTO dt inner join VENTA v
on dt.ID_VENTA=v.ID_VENTA where v.ID_VENTA=NEW.ID_VENTA;
UPDATE STOCK_PRODUCTO_TIENDA_ORIGEN AS stk
set stk.CANTIDAD = stk.CANTIDAD-NEW.CANTIDAD
where stk.ID_PRODUCTO = new.ID_PRODUCTO and stk.ID_TIENDA_ORIGEN = id_;

OPEN c;

SET x = 0;
size: LOOP
FETCH c INTO id_deta;



if x < new.CANTIDAD   then             -- check the loop control variable, the handler might've modified it
update DETALLE_ALMACEN_PRODUCTOS_COSTOS set ID_ESTADO_PRODUCTO_COSTO_ALMACEN=2 
WHERE ID_DETALLE_ALMACEN_PRODUCTOS_COSTOS=id_deta;            
-- close c;                  -- free resources
      ELSE    
    leave size;                    -- stop iterations 
       
end if;


SET  x = x + 1;
END LOOP size;
CLOSE c;


END//
DELIMITER ;
*/






DELIMITER //
CREATE TRIGGER inserta_detalles_factura
 AFTER INSERT ON DETALLE_FACTURA_VENTA_PRODUCTO
/*
usa este detalle, para que uses el ID_VENTA, a traves de eso vas a poder actualizar un campo
en la venta que se llame : Utilidad y que sea la resta del costo en almacen entre el precio de venta
*/
 FOR EACH ROW
 BEGIN
declare x int(11) default 0;
declare id_ int(12) default 0;

/*
agregado para las salidas en almacen
*/
DECLARE id_cliente  int(11) default 0;
DECLARE desc_ubicacion VARCHAR(370) default '';


DECLARE id_deta  int(50);
DECLARE _cant int(10);
DECLARE _resto int(10);
DECLARE _ID_TIENDA  INT(11);
DECLARE err_no_more_records CONDITION FOR 1329;
DECLARE c CURSOR FOR select dt.ID_DETALLE_ALMACEN_PRODUCTOS, dt.QUEDARON,dt.ID_TIENDA
,UF.NOMBRE_UBICACION_FISICA from DETALLE_ALMACEN_PRODUCTOS dt 
inner join UBICACION_FISICA UF on UF.ID_UBICACION_FISICA = dt.ID_UBICACION_FISICA
where dt.ID_PRODUCTO=new.ID_PRODUCTO and dt.ID_ESTADO_PRODUCTO_COSTO_ALMACEN=1
order by dt.COSTO;
DECLARE EXIT HANDLER FOR err_no_more_records



BEGIN
END;

/*agregado un nuevo into para cliente.*/
select distinct v.ID_TIENDA, v.ID_CLIENTE into id_ , id_cliente from DETALLE_FACTURA_VENTA_PRODUCTO dt inner join FACTURA_VENTA v
on dt.ID_FACTURA_VENTA=v.ID_FACTURA_VENTA where v.ID_FACTURA_VENTA=NEW.ID_FACTURA_VENTA;
UPDATE STOCK_PRODUCTO_TIENDA_ORIGEN AS stk
set stk.CANTIDAD = stk.CANTIDAD-NEW.CANTIDAD
where stk.ID_PRODUCTO = new.ID_PRODUCTO and stk.ID_TIENDA_ORIGEN = id_;

set _resto =new.CANTIDAD;
OPEN c;

SET x = 0;
size: LOOP
FETCH c INTO id_deta,_cant,_ID_TIENDA,desc_ubicacion;

if id_  = _ID_TIENDA and _cant <= _resto then



update DETALLE_ALMACEN_PRODUCTOS set ID_ESTADO_PRODUCTO_COSTO_ALMACEN=2,SALIERON=SALIERON+_cant,QUEDARON=0  
WHERE ID_DETALLE_ALMACEN_PRODUCTOS=id_deta;


/*
agregando la referencia a orden de salida en almacen
*/
insert ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS(ID_DETALLE_ALMACEN_PRODUCTOS,ID_CLIENTE,OBSERVACIONES_UBICACION,
FECHA_REGISTRO,CODIGO_FACTURA_BOLETA,CANTIDAD,ID_ESTADO_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS)
values (id_deta,id_cliente,desc_ubicacion, NOW(),NEW.ID_FACTURA_VENTA,_cant,1);



set _resto = _resto - _cant;
else

if id_  = _ID_TIENDA then
update DETALLE_ALMACEN_PRODUCTOS set ID_ESTADO_PRODUCTO_COSTO_ALMACEN=1,SALIERON=SALIERON + _resto,QUEDARON=QUEDARON-_resto
WHERE ID_DETALLE_ALMACEN_PRODUCTOS=id_deta;

/*
agregando la referencia a orden de salida en almacen
*/
insert ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS(ID_DETALLE_ALMACEN_PRODUCTOS,ID_CLIENTE,OBSERVACIONES_UBICACION,
FECHA_REGISTRO,CODIGO_FACTURA_BOLETA,CANTIDAD,ID_ESTADO_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS)
values (id_deta,id_cliente,desc_ubicacion,NOW(),NEW.ID_FACTURA_VENTA,_resto,1);


set _resto=0;
end if;


end if;


  if _resto=0 then
 leave size; 
           
end if;

END LOOP size;
CLOSE c;


END//
DELIMITER ;



/*
DELIMITER //
CREATE TRIGGER inserta_detalles_factura
 AFTER INSERT ON DETALLE_FACTURA_VENTA_PRODUCTO
 FOR EACH ROW
 BEGIN
declare id_ int(12) default 0;
select distinct v.ID_TIENDA into id_ from DETALLE_FACTURA_VENTA_PRODUCTO dt inner join FACTURA_VENTA v
on dt.ID_FACTURA_VENTA=v.ID_FACTURA_VENTA where v.ID_FACTURA_VENTA=NEW.ID_FACTURA_VENTA;
UPDATE STOCK_PRODUCTO_TIENDA_ORIGEN AS stk
set stk.CANTIDAD = stk.CANTIDAD-NEW.CANTIDAD
where stk.ID_PRODUCTO = new.ID_PRODUCTO and stk.ID_TIENDA_ORIGEN = id_;
 END//
DELIMITER ;

*/

DELIMITER //
CREATE TRIGGER inserta_detalles_cambio
 AFTER INSERT ON DETALLE_CAMBIO_PRODUCTO
 FOR EACH ROW
 BEGIN
declare id_ int(11) default 0;
select distinct v.ID_TIENDA into id_ from CAMBIO c inner join DETALLE_CAMBIO_PRODUCTO dt
on dt.ID_CAMBIO = c.ID_CAMBIO  inner join VENTA v on
v.ID_VENTA=c.ID_VENTA  where dt.ID_CAMBIO=NEW.ID_CAMBIO;


UPDATE STOCK_PRODUCTO_TIENDA_ORIGEN AS stk
set stk.CANTIDAD = stk.CANTIDAD + 1
where stk.ID_PRODUCTO = new.ID_PRODUCTO_CAMBIO and stk.ID_TIENDA_ORIGEN = id_;


UPDATE STOCK_PRODUCTO_TIENDA_ORIGEN AS stk
set stk.CANTIDAD = stk.CANTIDAD - 1
where stk.ID_PRODUCTO = new.ID_PRODUCTO_CAMBIADA and stk.ID_TIENDA_ORIGEN = id_;


 END//
DELIMITER ;


DELIMITER //
CREATE PROCEDURE VENTAS_FECHA( IN FECHA_INICIAL DATE,IN FECHA_FINAL DATE)
 BEGIN
select v.ID_VENTA as 'NUMERO', v.FECHA_VENTA as 'FECHA', t.NOMBRE_TIENDA as 'TIENDA',
tp.NOMBRE_TIPO_VENTA as 'TIPO',v.TOTAL_VENTA as 'TOTAL', p.NOMBRE_PRODUCTO as 'PRODUCTO' ,
dt.CANTIDAD, dt.PRECIO_VENTA, dt.DESCUENTO, dt.SUB_TOTAL from VENTA v inner join DETALLE_VENTA_PRODUCTO dt 
on dt.ID_VENTA = v.ID_VENTA inner join TIENDA t on t.ID_TIENDA = v.ID_TIENDA
inner join TIPO_VENTA tp on tp.ID_TIPO_VENTA=v.ID_TIPO_VENTA
inner join PRODUCTO p on dt.ID_PRODUCTO=p.ID_PRODUCTO 
where v.FECHA_VENTA between FECHA_INICIAL and FECHA_FINAL ORDER BY v.ID_VENTA;

 END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE PRODUCTOS_FECHA( IN FECHA_INICIAL DATE,IN FECHA_FINAL DATE)
 BEGIN
select p.NOMBRE_PRODUCTO, sum(dt.CANTIDAD) AS CANTIDAD from DETALLE_VENTA_PRODUCTO dt
inner join PRODUCTO p on p.ID_PRODUCTO = dt.ID_PRODUCTO inner join VENTA v on
dt.ID_VENTA = v.ID_VENTA
where v.FECHA_VENTA between FECHA_INICIAL and FECHA_FINAL 
group by (p.ID_PRODUCTO);
 END //
DELIMITER ;




/*
Agregado para realizar el canje de credito a letras pendiente.
*/

CREATE TABLE ESTADO_LETRAS_PAGO_CANJE(
ID_ESTADO_LETRAS_PAGO_CANJE INT(11) NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(100) ,
DESCRIPCION VARCHAR(170),
 PRIMARY KEY (ID_ESTADO_LETRAS_PAGO_CANJE) 
)ENGINE=InnoDB;

CREATE TABLE ESTADO_CANJE_ORDEN_COMPRA(
ID_ESTADO_CANJE_ORDEN_COMPRA INT(11) NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(100) ,
DESCRIPCION VARCHAR(170),
 PRIMARY KEY (ID_ESTADO_CANJE_ORDEN_COMPRA) 
)ENGINE=InnoDB;

CREATE TABLE CANJE_ORDEN_COMPRA(
ID_CANJE_ORDEN_COMPRA int(11) not null auto_increment,
ID_ORDEN_COMPRA int(11) not null,
FECHA_CREACION_CANJE DATE NOT NULL,
FECHA_PAGO DATE NOT NULL,
MONTO_CANJE decimal(9,2) not null default 0.0,
NUMERO_CUOTAS INT(1) NOT NULL DEFAULT 1,
NOMBRE_BANCO_PAGAR VARCHAR(150) NOT NULL DEFAULT '',
NUMERO_CUENTA VARCHAR(210) NOT NULL DEFAULT '',
OBSERVACIONES VARCHAR(300) NOT NULL DEFAULT '',
ID_ESTADO_CANJE_ORDEN_COMPRA INT(11) ,
 PRIMARY KEY (ID_CANJE_ORDEN_COMPRA),
 FOREIGN KEY (ID_ORDEN_COMPRA) REFERENCES ORDEN_COMPRA (ID_ORDEN_COMPRA),
 FOREIGN KEY (ID_ESTADO_CANJE_ORDEN_COMPRA) REFERENCES ESTADO_CANJE_ORDEN_COMPRA (ID_ESTADO_CANJE_ORDEN_COMPRA)
)ENGINE=InnoDB;


CREATE TABLE LETRAS_PAGO_CANJE(
ID_LETRAS_PAGO_CANJE INT (11) NOT NULL AUTO_INCREMENT,
ID_CANJE_ORDEN_COMPRA int(11) not null ,
FECHA_PAGO DATE NOT NULL,
FECHA_REALIZO_PAGO DATE NOT NULL,
TOTAL_LETRA decimal(9,2) not null default 0.0,
OBSERVACIONES VARCHAR(300) NOT NULL DEFAULT '',
ID_ESTADO_LETRAS_PAGO_CANJE INT(11),
 PRIMARY KEY (ID_LETRAS_PAGO_CANJE),
 FOREIGN KEY (ID_ESTADO_LETRAS_PAGO_CANJE) REFERENCES ESTADO_LETRAS_PAGO_CANJE (ID_ESTADO_LETRAS_PAGO_CANJE),
 FOREIGN KEY (ID_CANJE_ORDEN_COMPRA) REFERENCES CANJE_ORDEN_COMPRA (ID_CANJE_ORDEN_COMPRA)
)ENGINE=InnoDB;


/*Agregado*/
create table DESARROLLADOR(
ID_DESARROLLADOR INT(3) NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(200),
PRIMARY KEY (ID_DESARROLLADOR)
)ENGINE=InnoDB;



DELIMITER //
CREATE TRIGGER inserta_detalles_canje
AFTER INSERT ON CANJE_ORDEN_COMPRA
FOR EACH ROW
BEGIN
DECLARE x  INT;
DECLARE CUOTA  DECIMAL(9,2);
SET CUOTA = NEW.MONTO_CANJE/NEW.NUMERO_CUOTAS;
SET x = 0;
WHILE x  < NEW.NUMERO_CUOTAS DO
insert into LETRAS_PAGO_CANJE(ID_CANJE_ORDEN_COMPRA ,FECHA_PAGO,
FECHA_REALIZO_PAGO,TOTAL_LETRA,OBSERVACIONES,ID_ESTADO_LETRAS_PAGO_CANJE) VALUES(new.ID_CANJE_ORDEN_COMPRA ,ADDDATE(NEW.FECHA_PAGO, INTERVAL x MONTH),
NEW.FECHA_PAGO,CUOTA,x+1,1);
SET  x = x + 1;
	              END WHILE;
END//
DELIMITER ;



/*
Modulo de produccion , a traves de materia prima y procesos de producción
*/

CREATE TABLE UNIDAD_MEDIDA(
ID_UNIDAD_MEDIDA int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_UNIDAD_MEDIDA VARCHAR(50) NOT NULL default '',
DESCRIPCION VARCHAR(170) NOT NULL default '',
PRIMARY KEY(ID_UNIDAD_MEDIDA)
)ENGINE=InnoDB;

CREATE TABLE MATERIA_PRIMA(
ID_MATERIA_PRIMA int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_MATERIA_PRIMA VARCHAR(150) NOT NULL default '',
ID_UNIDAD_MEDIDA int(11),
DESCRIPCION VARCHAR(200) NOT NULL default '',
PRIMARY KEY(ID_MATERIA_PRIMA),
FOREIGN KEY (ID_UNIDAD_MEDIDA) REFERENCES UNIDAD_MEDIDA (ID_UNIDAD_MEDIDA)
)ENGINE=InnoDB;


CREATE TABLE STOCK_MATERIA_PRIMA_TIENDA_ORIGEN(
ID_MATERIA_PRIMA INT(11) NOT NULL,
ID_TIENDA_ORIGEN  INT(11) NOT NULL,
CANTIDAD DECIMAL(12,4) NOT NULL DEFAULT 0,
ULTIMA_FECHA_INGRESO DATE NOT NULL,
DESCRIPCION VARCHAR(370) DEFAULT '',
PRIMARY KEY (ID_MATERIA_PRIMA,ID_TIENDA_ORIGEN),
FOREIGN KEY (ID_MATERIA_PRIMA) REFERENCES MATERIA_PRIMA (ID_MATERIA_PRIMA),
FOREIGN KEY (ID_TIENDA_ORIGEN) REFERENCES TIENDA (ID_TIENDA)
)ENGINE=InnoDB;



CREATE TABLE INGRESO_MATERIA_PRIMA_TIENDA(
ID_INGRESO_MATERIA_PRIMA_TIENDA INT(11) NOT NULL AUTO_INCREMENT,
ID_TIENDA INT(11) NOT NULL,
ID_MATERIA_PRIMA INT(11) NOT NULL,
CANTIDAD DECIMAL(12,4) NOT NULL DEFAULT 0,
FECHA_INGRESO DATE NOT NULL,
MOTIVO VARCHAR(300) NOT NULL DEFAULT '',
PRIMARY KEY (ID_INGRESO_MATERIA_PRIMA_TIENDA),
FOREIGN KEY (ID_TIENDA) REFERENCES TIENDA (ID_TIENDA),
FOREIGN KEY (ID_MATERIA_PRIMA) REFERENCES MATERIA_PRIMA (ID_MATERIA_PRIMA)
)ENGINE=InnoDB;


CREATE TABLE SALIDA_MATERIA_PRIMA_TIENDA(
ID_SALIDA_MATERIA_PRIMA_TIENDA INT(11) NOT NULL AUTO_INCREMENT,
ID_TIENDA INT(11) NOT NULL,
ID_MATERIA_PRIMA INT(11) NOT NULL,
CANTIDAD DECIMAL(12,4) NOT NULL DEFAULT 0,
FECHA_SALIDA DATE NOT NULL,
MOTIVO VARCHAR(300) NOT NULL DEFAULT '',
PRIMARY KEY (ID_SALIDA_MATERIA_PRIMA_TIENDA),
FOREIGN KEY (ID_MATERIA_PRIMA) REFERENCES MATERIA_PRIMA (ID_MATERIA_PRIMA),
FOREIGN KEY (ID_TIENDA) REFERENCES TIENDA (ID_TIENDA)
)ENGINE=InnoDB;




CREATE TABLE FORMULACION(
ID_FORMULACION int(11) NOT NULL AUTO_INCREMENT,
FECHA_REGISTRO DATE NOT NULL,
/*
ESTE PRODUCTO ES EL PRODUCTO PRINCIPAL
ES DECIR EL RESULTADO DE LAS MATERIAS PRIMAS
*/
ID_PRODUCTO INT(11) NOT NULL,
PALABRA_CLAVE VARCHAR(250) NOT NULL DEFAULT '',
DESCRIPCION VARCHAR(800) NOT NULL DEFAULT '',
PRIMARY KEY (ID_FORMULACION),
FOREIGN KEY (ID_PRODUCTO)
REFERENCES PRODUCTO (ID_PRODUCTO)
)ENGINE=InnoDB;


CREATE TABLE DETALLE_FORMULACION_INSUMOS(
ID_FORMULACION int(11) NOT NULL ,
ID_MATERIA_PRIMA INT(11) NOT NULL,
PROPORCION DECIMAL(9,3) NOT NULL DEFAULT 0,
PRIMARY KEY (ID_FORMULACION,ID_MATERIA_PRIMA),
FOREIGN KEY (ID_FORMULACION )
REFERENCES FORMULACION (ID_FORMULACION ),
FOREIGN KEY (ID_MATERIA_PRIMA)
REFERENCES MATERIA_PRIMA (ID_MATERIA_PRIMA)
)ENGINE=InnoDB;


CREATE TABLE PRODUCCION_ALMACEN(
ID_PRODUCCION_ALMACEN int(11) NOT NULL AUTO_INCREMENT,
/* POR AQUI PUEDE IR A ORDEN DE PRODUCCION*/
ID_TIENDA_ORIGEN  INT(11) NOT NULL,
/* TIENDA ORGIEN ES EL ALMACEN DE DONDE SE EXTRAE LOS INSUMOS*/
ID_FORMULACION int(11) ,
FECHA_REGISTRO DATE NOT NULL,
CANTIDAD_PRODUCTO_TERMINADO INT(11) NOT NULL,
DESCRIPCION VARCHAR(350) NOT NULL DEFAULT '',
PRIMARY KEY (ID_PRODUCCION_ALMACEN),
FOREIGN KEY (ID_FORMULACION )
REFERENCES FORMULACION (ID_FORMULACION ),
FOREIGN KEY (ID_TIENDA_ORIGEN) REFERENCES TIENDA (ID_TIENDA)
)ENGINE=InnoDB;


DELIMITER //
CREATE TRIGGER inserta_produccion_almacen
after INSERT ON PRODUCCION_ALMACEN
 FOR EACH ROW
 BEGIN
DECLARE a DECIMAL(9,3)  DEFAULT 0;
DECLARE x,y  int(11);
DECLARE err_no_more_records CONDITION FOR 1329;
DECLARE c CURSOR FOR select p.CANTIDAD_PRODUCTO_TERMINADO,dt.ID_MATERIA_PRIMA, dt.PROPORCION  from DETALLE_FORMULACION_INSUMOS dt inner join FORMULACION f
on f.ID_FORMULACION = dt.ID_FORMULACION inner join PRODUCCION_ALMACEN p 
on p.ID_FORMULACION = f.ID_FORMULACION where p.ID_PRODUCCION_ALMACEN = NEW.ID_PRODUCCION_ALMACEN;
DECLARE EXIT HANDLER FOR err_no_more_records
BEGIN
END;
OPEN c;
size: LOOP
FETCH c INTO x,y,a;

UPDATE STOCK_MATERIA_PRIMA_TIENDA_ORIGEN AS stk
set stk.CANTIDAD = stk.CANTIDAD-(x*a)
where stk.ID_MATERIA_PRIMA = y and stk.ID_TIENDA_ORIGEN = NEW.ID_TIENDA_ORIGEN;


END LOOP size;
CLOSE c;

 END//
DELIMITER ;

/* Creando la seccion de Costos en almacen, esta tabla no es usada. */
CREATE TABLE DETALLE_ALMACEN_PRODUCTOS_COSTOS(
ID_DETALLE_ALMACEN_PRODUCTOS_COSTOS INT (50) NOT NULL AUTO_INCREMENT,
ID_PRODUCTO int(11) not null ,
COSTO DECIMAL(9,3) NOT NULL DEFAULT 0,
FECHA_ENTRADA DATETIME NOT NULL,
FECHA_SALIDA DATETIME DEFAULT '1990-01-01 00:00:00',
ID_PROCEDENCIA_PRODUCTO_ALMACEN int(11) not null ,
OBSERVACIONES VARCHAR(300) NOT NULL DEFAULT '',
ID_ESTADO_PRODUCTO_COSTO_ALMACEN int(3),
ID_TIENDA INT(11) NOT NULL,
PRIMARY KEY (ID_DETALLE_ALMACEN_PRODUCTOS_COSTOS),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
FOREIGN KEY (ID_PROCEDENCIA_PRODUCTO_ALMACEN) REFERENCES PROCEDENCIA_PRODUCTO_ALMACEN (ID_PROCEDENCIA_PRODUCTO_ALMACEN),
FOREIGN KEY (ID_ESTADO_PRODUCTO_COSTO_ALMACEN) REFERENCES ESTADO_PRODUCTO_COSTO_ALMACEN (ID_ESTADO_PRODUCTO_COSTO_ALMACEN),
FOREIGN KEY (ID_TIENDA) REFERENCES TIENDA (ID_TIENDA)
)ENGINE=InnoDB;

/*
Esta Tabla no es usada.
*/
CREATE TABLE ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS_COSTOS(
ID_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS_COSTOS INT (50) NOT NULL AUTO_INCREMENT,
ID_DETALLE_ALMACEN_PRODUCTOS_COSTOS INT(50) NOT NULL,
ID_CLIENTE INT(11) NOT NULL,
OBSERVACIONES_UBICACION VARCHAR(300) NOT NULL DEFAULT '',
FECHA_REGISTRO DATETIME NOT NULL,
CODIGO_FACTURA_BOLETA VARCHAR(150) NOT NULL,
PRIMARY KEY (ID_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS_COSTOS),
FOREIGN KEY (ID_DETALLE_ALMACEN_PRODUCTOS_COSTOS) REFERENCES DETALLE_ALMACEN_PRODUCTOS_COSTOS (ID_DETALLE_ALMACEN_PRODUCTOS_COSTOS),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
)ENGINE=InnoDB;


/*
DELIMITER //
CREATE TRIGGER inserta_ingreso_almacen
 AFTER INSERT ON INGRESO_PRODUCTO_TIENDA
 FOR EACH ROW
 BEGIN
DECLARE x  INT;
SET x = 0;
WHILE x  < NEW.CANTIDAD DO

insert into DETALLE_ALMACEN_PRODUCTOS_COSTOS(ID_PRODUCTO,COSTO,FECHA_ENTRADA,FECHA_SALIDA,ID_PROCEDENCIA_PRODUCTO_ALMACEN,OBSERVACIONES,ID_ESTADO_PRODUCTO_COSTO_ALMACEN,ID_TIENDA)
values (new.ID_PRODUCTO,NEW.COSTO_UNITARIO,NEW.FECHA_INGRESO,'1990-01-01 00:00:00',1,new.MOTIVO,1,new.ID_TIENDA);
SET  x = x + 1;
	              END WHILE;

 END//
DELIMITER ;
*/

/*  Crando el detalle de almacen de una forma mas eficiente */
/* ESTA ES LA TABLA QUE CONTROLA LAS SALIDAS DE ALMACEN, es casi como un stock de almacen al detalle*/
CREATE TABLE DETALLE_ALMACEN_PRODUCTOS(
ID_DETALLE_ALMACEN_PRODUCTOS INT (15) NOT NULL AUTO_INCREMENT,
ID_PRODUCTO INT(11) NOT NULL,
COSTO DECIMAL(9,3) NOT NULL DEFAULT 0,
ID_TIENDA  INT(11) NOT NULL,
CANTIDAD INT(10) NOT NULL,
SALIERON INT(10) NOT NULL,
QUEDARON INT(10) NOT NULL,
FECHA_INGRESO DATE NOT NULL,
FECHA_VENCIMIENTO DATE NOT NULL DEFAULT '1990-01-01',
DESCRIPCION_MOTIVO VARCHAR(370) DEFAULT '',
/*DESCRIPCION_UBICACION VARCHAR(370) DEFAULT '',*/
ID_UBICACION_FISICA int(11) NOT NULL ,
ID_PROCEDENCIA_PRODUCTO_ALMACEN int(11) not null ,
ID_ESTADO_PRODUCTO_COSTO_ALMACEN int(3),
FOREIGN KEY (ID_ESTADO_PRODUCTO_COSTO_ALMACEN) REFERENCES ESTADO_PRODUCTO_COSTO_ALMACEN (ID_ESTADO_PRODUCTO_COSTO_ALMACEN),
PRIMARY KEY (ID_DETALLE_ALMACEN_PRODUCTOS),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
FOREIGN KEY (ID_PROCEDENCIA_PRODUCTO_ALMACEN) REFERENCES PROCEDENCIA_PRODUCTO_ALMACEN (ID_PROCEDENCIA_PRODUCTO_ALMACEN),
FOREIGN KEY (ID_TIENDA) REFERENCES TIENDA (ID_TIENDA),
FOREIGN KEY (ID_UBICACION_FISICA) REFERENCES UBICACION_FISICA (ID_UBICACION_FISICA)
)ENGINE=InnoDB;


/*CREAMOS UNO NUEVO*/
DELIMITER //
CREATE TRIGGER inserta_ingreso_almacen
 AFTER INSERT ON INGRESO_PRODUCTO_TIENDA
 FOR EACH ROW
 BEGIN

insert into DETALLE_ALMACEN_PRODUCTOS(
ID_PRODUCTO,
COSTO,
ID_TIENDA,
CANTIDAD,
SALIERON,
QUEDARON,
FECHA_INGRESO,
FECHA_VENCIMIENTO,
DESCRIPCION_MOTIVO,
ID_UBICACION_FISICA,
ID_PROCEDENCIA_PRODUCTO_ALMACEN,
ID_ESTADO_PRODUCTO_COSTO_ALMACEN)
values (new.ID_PRODUCTO,NEW.COSTO_UNITARIO,new.ID_TIENDA,NEW.CANTIDAD,0,new.CANTIDAD,new.FECHA_INGRESO,new.FECHA_VENCIMIENTO ,new.MOTIVO,new.ID_UBICACION_FISICA,1,1);

 END//
DELIMITER ;





/*
DELIMITER //
CREATE TRIGGER inserta_ingreso_almacen
 AFTER INSERT ON INGRESO_PRODUCTO_TIENDA
 FOR EACH ROW
 BEGIN

insert into DETALLE_ALMACEN_PRODUCTOS(
ID_PRODUCTO,
COSTO,
ID_TIENDA,
CANTIDAD,
SALIERON,
QUEDARON,
FECHA_INGRESO,
FECHA_VENCIMIENTO,
DESCRIPCION_MOTIVO,
DESCRIPCION_UBICACION,
ID_PROCEDENCIA_PRODUCTO_ALMACEN,
ID_ESTADO_PRODUCTO_COSTO_ALMACEN)
values (new.ID_PRODUCTO,NEW.COSTO_UNITARIO,new.ID_TIENDA,NEW.CANTIDAD,0,new.CANTIDAD,new.FECHA_INGRESO,new.FECHA_VENCIMIENTO ,new.MOTIVO,new.UBICACION,1,1);

 END//
DELIMITER ;
*/


/*
creando las ordenes de salida para el almacenero.
*/


CREATE TABLE ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS(
ID_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS_COSTOS INT (50) NOT NULL AUTO_INCREMENT,
ID_DETALLE_ALMACEN_PRODUCTOS INT (15) not null,
ID_CLIENTE INT(11) NOT NULL,
OBSERVACIONES_UBICACION VARCHAR(300) NOT NULL DEFAULT '',
FECHA_REGISTRO DATE NOT NULL,
CODIGO_FACTURA_BOLETA VARCHAR(150) NOT NULL,
CANTIDAD INT(10) NOT NULL,
ID_ESTADO_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS int(3) not null,
PRIMARY KEY (ID_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS_COSTOS),
FOREIGN KEY (ID_DETALLE_ALMACEN_PRODUCTOS) REFERENCES DETALLE_ALMACEN_PRODUCTOS (ID_DETALLE_ALMACEN_PRODUCTOS),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
FOREIGN KEY (ID_ESTADO_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS) REFERENCES ESTADO_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS (ID_ESTADO_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS)
)ENGINE=InnoDB;




/*MODULO CONTABLE*/


/*Agregado*/
CREATE TABLE TIPO_CUENTA_CONTABLE(
ID_TIPO_CUENTA_CONTABLE int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_TIPO_CUENTA_CONTABLE VARCHAR(170) NOT NULL default '',
DESCRIPCION VARCHAR(250) NOT NULL default '',
PRIMARY KEY (ID_TIPO_CUENTA_CONTABLE)
)ENGINE=InnoDB;


/*Agregado*/
CREATE TABLE TIPO_ELEMENTO(
ID_TIPO_ELEMENTO int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_TIPO_ELEMENTO VARCHAR(170) NOT NULL default '',
DESCRIPCION VARCHAR(250) NOT NULL default '',
PRIMARY KEY (ID_TIPO_ELEMENTO)
)ENGINE=InnoDB;

/*Agregado*/
CREATE TABLE SUB_ELEMENTO(
ID_SUB_ELEMENTO int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_SUB_ELEMENTO VARCHAR(170) NOT NULL default '',
DESCRIPCION VARCHAR(250) NOT NULL default '',
PRIMARY KEY (ID_SUB_ELEMENTO)
)ENGINE=InnoDB;


/*Agregado*/
CREATE TABLE CUENTA_CONTABLE(
ID_CUENTA_CONTABLE int(11) NOT NULL AUTO_INCREMENT,
ID_TIPO_CUENTA_CONTABLE int(11) not null,
ID_TIPO_ELEMENTO int(11) not null,
ID_SUB_ELEMENTO int(11) not null,
NUMERO int not null,
NOMBRE_CUENTA_CONTABLE VARCHAR(170) NOT NULL default '',
DESCRIPCION VARCHAR(250) NOT NULL default '',
PRIMARY KEY (ID_CUENTA_CONTABLE),
FOREIGN KEY (ID_TIPO_CUENTA_CONTABLE) REFERENCES TIPO_CUENTA_CONTABLE (ID_TIPO_CUENTA_CONTABLE),
FOREIGN KEY (ID_TIPO_ELEMENTO) REFERENCES TIPO_ELEMENTO (ID_TIPO_ELEMENTO),
FOREIGN KEY (ID_SUB_ELEMENTO) REFERENCES SUB_ELEMENTO (ID_SUB_ELEMENTO)
)ENGINE=InnoDB;



/*
Agregando Modulo de Atencion al CLiente -- 
*/



/*
SE HA CAMBIADO ESTA TABLA 
*/
CREATE TABLE ACTIVIDAD(
ID_ACTIVIDAD int(11) NOT NULL AUTO_INCREMENT,
ID_CLIENTE INT(11) NOT NULL,
DESCRIPCION_ACTIVIDAD VARCHAR(500) NOT NULL default '',
FECHA DATETIME NOT NULL,
PRIMARY KEY (ID_ACTIVIDAD),
FOREIGN KEY (ID_CLIENTE)  REFERENCES CLIENTE(ID_CLIENTE)
)ENGINE=InnoDB;

CREATE TABLE CLIENTE_POTENCIAL(
ID_CLIENTE_POTENCIAL int(11) NOT NULL AUTO_INCREMENT,
FECHA_REGISTRO DATE NOT NULL,
CLIENTE_RAZON_SOCIAL VARCHAR(150) NOT NULL default '',
FECHA_CUMPLEANIOS DATE NOT NULL,
DIRECCION VARCHAR(350) NOT NULL default '',
DNI VARCHAR(12) NOT NULL default '',
ESTADO INT(1) NOT NULL DEFAULT 1,
TELEFONO VARCHAR(50) NOT NULL default '',
PRIMARY KEY (ID_CLIENTE_POTENCIAL)
)ENGINE=InnoDB;

CREATE TABLE CONTRATO_FUMIGACION(
ID_CONTRATO_FUMIGACION int(11) NOT NULL AUTO_INCREMENT,
ID_VENTA INT(11) NOT NULL,
FECHA_VENTA DATE NOT NULL,
/*Agregado*/
FECHA_VENTA_EMISION DATE NOT NULL,
FECHA_HORA_FUMIGACION DATETIME NOT NULL,
PLAGA VARCHAR(170) NOT NULL DEFAULT '',
DESCRIPCION VARCHAR(500) NOT NULL DEFAULT '',
TOTAL_SERVICIO DECIMAL(9,2) NOT NULL DEFAULT 0,
CUENTA DECIMAL(9,2) NOT NULL DEFAULT 0,
SALDO DECIMAL(9,2) NOT NULL DEFAULT 0,
PRIMARY KEY (ID_CONTRATO_FUMIGACION),
FOREIGN KEY (ID_VENTA)  REFERENCES VENTA (ID_VENTA)
)ENGINE=InnoDB;



CREATE TABLE DETALLE_FUMIGACION_PRODUCTO(
ID_DETALLE_FUMIGACION_PRODUCTO int(11) NOT NULL AUTO_INCREMENT,
ID_CONTRATO_FUMIGACION int(11) NOT NULL,
ID_PRODUCTO INT(11) NOT NULL,
CANTIDAD INT NOT NULL,
UTILIZO DECIMAL (9,3) NOT NULL DEFAULT 0.0,
QUEDO DECIMAL (9,3) NOT NULL DEFAULT 0.0,
PRIMARY KEY (ID_DETALLE_FUMIGACION_PRODUCTO),
FOREIGN KEY (ID_CONTRATO_FUMIGACION) REFERENCES  CONTRATO_FUMIGACION(ID_CONTRATO_FUMIGACION),
FOREIGN KEY (ID_PRODUCTO) REFERENCES  PRODUCTO(ID_PRODUCTO)
)ENGINE=InnoDB;


CREATE TABLE REPORTE_DESRATIZACION(
ID_REPORTE_DESRATIZACION int(11) NOT NULL AUTO_INCREMENT,
ID_CONTRATO_FUMIGACION int(11) NOT NULL,
FECHA DATE NOT NULL,
ID_EMPLEADO INT(11) NOT NULL,
DESCRIPCION_CLIENTE VARCHAR(500) NOT NULL default '',
HORA_INICIO VARCHAR(20) NOT NULL default '',
DURACION_MINUTOS INT NOT NULL ,
NUMERO_ESTACIONES_INSTALADAS INT NOT NULL,
CANTIDAD_PRODUCTO_UTILIZADO VARCHAR(35) NOT NULL default '',
PORCENTAJE_AVANCE INT(4) NOT NULL,
COMENTARIOS_CLIENTE VARCHAR(500) NOT NULL default '',
OBSERVACIONES_CLIENTE VARCHAR(500) NOT NULL default '',
REQUERIMIENTOS_DIA_SIGUIENTE VARCHAR(500) NOT NULL default '',
PRIMARY KEY (ID_REPORTE_DESRATIZACION),
FOREIGN KEY (ID_CONTRATO_FUMIGACION) REFERENCES CONTRATO_FUMIGACION (ID_CONTRATO_FUMIGACION),
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO)
)ENGINE=InnoDB;



CREATE TABLE REPORTE_FUMIGACION(
ID_REPORTE_FUMIGACION int(11) NOT NULL AUTO_INCREMENT,
ID_CONTRATO_FUMIGACION int(11) NOT NULL,
FECHA DATE NOT NULL,
ID_EMPLEADO INT(11) NOT NULL,
DESCRIPCION_CLIENTE VARCHAR(350) NOT NULL default '',
CARACTERISTICAS_ALBIENTE VARCHAR(100) NOT NULL default '',
AREA_ESTIMADA VARCHAR(20) NOT NULL default '',
AREA_TRATADA VARCHAR(20) NOT NULL default '',
TIPO_PLAGA varchar(100) not null,
PORCENTAJE_INFESTACION INT NOT NULL,
PORCENTAJE_CANTIDAD_FUENTES_ALIMENTARIAS INT NOT NULL,
MANEJO_RESIDUOS_ALIMENTICIOS VARCHAR(45) NOT NULL,
PORCENTAJE_HIGIENE INT NOT NULL,
MOBILIARIO VARCHAR(250) NOT NULL default '',
DISPERCION VARCHAR(400) NOT NULL default '',
PORCENTAJE_MACHOS INT NOT NULL,
PORCENTAJE_HEMBRAS INT NOT NULL,
TAPADO_GRIETAS VARCHAR(100) NOT NULL,
ZONAS_EQUIPOS VARCHAR(370) NOT NULL default '',
UTILIZACION_PRODUCTO VARCHAR(500) NOT NULL default '',
PRIMARY KEY (ID_REPORTE_FUMIGACION ),
FOREIGN KEY (ID_CONTRATO_FUMIGACION) REFERENCES CONTRATO_FUMIGACION (ID_CONTRATO_FUMIGACION),
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO)
)ENGINE=InnoDB;







/*Agregado*/
CREATE TABLE TIPO_SERVICIO(
ID_TIPO_SERVICIO int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_TIPO_SERVICIO VARCHAR(170) NOT NULL default '',
DESCRIPCION VARCHAR(250) NOT NULL default '',
PRIMARY KEY (ID_TIPO_SERVICIO)
)ENGINE=InnoDB;


CREATE TABLE TIPO_PLAGA(
ID_TIPO_PLAGA int(11) NOT NULL AUTO_INCREMENT,
NOMBRE_TIPO_PLAGA VARCHAR(170) NOT NULL default '',
DESCRIPCION VARCHAR(250) NOT NULL default '',
PRIMARY KEY (ID_TIPO_PLAGA)
)ENGINE=InnoDB;

CREATE TABLE SERVICIO(
ID_SERVICIO int(11) NOT NULL AUTO_INCREMENT,
ID_TIPO_SERVICIO INT(11) NOT NULL, 
FECHA_REGISTRO DATE NOT NULL,
NOMBRE_SERVICIO VARCHAR(250) NOT NULL DEFAULT '',
PALABRA_CLAVE VARCHAR(250) NOT NULL DEFAULT '',
DESCRIPCION VARCHAR(800) NOT NULL DEFAULT '',
PRIMARY KEY (ID_SERVICIO),
FOREIGN KEY (ID_TIPO_SERVICIO) REFERENCES TIPO_SERVICIO (ID_TIPO_SERVICIO)
)ENGINE=InnoDB;

/*
SE DEBE RESTAR DE LOS DETALLES DE ALMACEN, PARA NO DESCUADRAR EL CANTIDAD SALE QUEDA.
SE HA CAMBIADO ESTA TABLA+++
*/

CREATE TABLE DETALLE_SERVICIO_PRODUCTO(
ID_SERVICIO int(11) NOT NULL ,
ID_PRODUCTO INT(11) NOT NULL,
CANTIDAD INT NOT NULL DEFAULT 0,
UTILIZO DECIMAL (9,3) NOT NULL DEFAULT 0.0,
QUEDO DECIMAL (9,3) NOT NULL DEFAULT 0.0,
PRIMARY KEY (ID_SERVICIO,ID_PRODUCTO),
FOREIGN KEY (ID_SERVICIO)
REFERENCES SERVICIO (ID_SERVICIO),
FOREIGN KEY (ID_PRODUCTO)
REFERENCES PRODUCTO (ID_PRODUCTO)
)ENGINE=InnoDB;


/* CODIGO DE BARRAS */

CREATE TABLE INVENTARIO_FISICO(
ID_INVENTARIO_FISICO int(11) NOT NULL AUTO_INCREMENT,
OBERVACIONES VARCHAR(100) NOT NULL DEFAULT "",
FECHA_INICIO DATE NOT NULL ,
FECHA_TERMINO DATE NOT NULL ,
ID_TIENDA int(11) NOT NULL,
PRIMARY KEY (ID_INVENTARIO_FISICO),
FOREIGN KEY (ID_TIENDA) REFERENCES TIENDA (ID_TIENDA)
)ENGINE=InnoDB;

CREATE TABLE DETALLE_INVENTARIO_UBICACION_FISICA(
ID_DETALLE_INVENTARIO_UBICACION_FISICA int(11) NOT NULL AUTO_INCREMENT,
ID_INVENTARIO_FISICO int(11) not null,
ID_UBICACION_FISICA int(11) NOT NULL,
PRIMARY KEY (ID_DETALLE_INVENTARIO_UBICACION_FISICA),
FOREIGN KEY (ID_INVENTARIO_FISICO) REFERENCES INVENTARIO_FISICO (ID_INVENTARIO_FISICO),
FOREIGN KEY (ID_UBICACION_FISICA) REFERENCES UBICACION_FISICA (ID_UBICACION_FISICA)
)ENGINE=InnoDB;

CREATE TABLE DETALLE_UBICACION_FISICA_PRODUCTO(
ID_DETALLE_UBICACION_FISICA_PRODUCTO int(11) NOT NULL AUTO_INCREMENT,
ID_DETALLE_INVENTARIO_UBICACION_FISICA int(11) NOT NULL,
ID_PRODUCTO int(11) NOT NULL,
CANTIDAD INT NOT NULL default 1,
PRIMARY KEY (ID_DETALLE_UBICACION_FISICA_PRODUCTO),
FOREIGN KEY (ID_DETALLE_INVENTARIO_UBICACION_FISICA) REFERENCES DETALLE_INVENTARIO_UBICACION_FISICA (ID_DETALLE_INVENTARIO_UBICACION_FISICA),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
)ENGINE=InnoDB;





CREATE TABLE VENTA_RAPIDA(
ID_VENTA_RAPIDA INT(11) NOT NULL AUTO_INCREMENT,
FECHA_VENTA DATE NOT NULL ,
ID_TIENDA int(11) NOT NULL,
PRIMARY KEY (ID_VENTA_RAPIDA),
FOREIGN KEY (ID_TIENDA) REFERENCES TIENDA (ID_TIENDA)
)ENGINE=InnoDB;

CREATE TABLE DETALLE_VENTA_RAPIDA_PRODUCTO(
ID_DETALLE_VENTA_RAPIDA_PRODUCTO INT(11) NOT NULL AUTO_INCREMENT,
ID_VENTA_RAPIDA INT(11) NOT NULL,
ID_CLIENTE int(11) NOT NULL,
ID_PRODUCTO INT(11) NOT NULL,
PRECIO_VENTA DECIMAL (9,2) NOT NULL,
CANTIDAD INT NOT NULL DEFAULT 1,
PRIMARY KEY (ID_DETALLE_VENTA_RAPIDA_PRODUCTO),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
FOREIGN KEY (ID_VENTA_RAPIDA) REFERENCES VENTA_RAPIDA (ID_VENTA_RAPIDA)
)ENGINE=InnoDB;



DELIMITER //
CREATE TRIGGER inserta_venta_rapida
 AFTER INSERT ON DETALLE_VENTA_RAPIDA_PRODUCTO
 FOR EACH ROW
 BEGIN

declare x int(11) default 0;
declare id_ int(11) default 0;

/*
agregado para las salidas en almacen
*/
DECLARE id_cliente  int(11) default 0;
DECLARE desc_ubicacion VARCHAR(370) default '';



DECLARE id_deta  int(50);
DECLARE _cant int(10);
DECLARE _resto int(10);
DECLARE _ID_TIENDA  INT(11);
DECLARE err_no_more_records CONDITION FOR 1329;


DECLARE c CURSOR FOR select dt.ID_DETALLE_ALMACEN_PRODUCTOS, dt.QUEDARON,dt.ID_TIENDA
,UF.NOMBRE_UBICACION_FISICA from DETALLE_ALMACEN_PRODUCTOS dt 
inner join UBICACION_FISICA UF on UF.ID_UBICACION_FISICA = dt.ID_UBICACION_FISICA
where dt.ID_PRODUCTO=new.ID_PRODUCTO and dt.ID_ESTADO_PRODUCTO_COSTO_ALMACEN=1

order by dt.COSTO;

DECLARE EXIT HANDLER FOR err_no_more_records

BEGIN
END;

select distinct v.ID_TIENDA,dt.ID_CLIENTE  into id_,id_cliente from DETALLE_VENTA_RAPIDA_PRODUCTO dt 
inner join VENTA_RAPIDA v
on dt.ID_VENTA_RAPIDA=v.ID_VENTA_RAPIDA where v.ID_VENTA_RAPIDA=NEW.ID_VENTA_RAPIDA;

UPDATE STOCK_PRODUCTO_TIENDA_ORIGEN AS stk
set stk.CANTIDAD = stk.CANTIDAD-NEW.CANTIDAD
where stk.ID_PRODUCTO = new.ID_PRODUCTO and stk.ID_TIENDA_ORIGEN = id_;
/*  TIENES QUE AGERGAR LAS ORDENES DE SALIDA */
/* AGREGAR EL REGISTRO DE DECREMENTO EN EL DETALLE*/

set _resto =new.CANTIDAD;
OPEN c;


SET x = 0;
size: LOOP
FETCH c INTO id_deta,_cant,_ID_TIENDA,desc_ubicacion;

if id_  = _ID_TIENDA and _cant <= _resto then



update DETALLE_ALMACEN_PRODUCTOS set ID_ESTADO_PRODUCTO_COSTO_ALMACEN=2,SALIERON=SALIERON+_cant,QUEDARON=0  
WHERE ID_DETALLE_ALMACEN_PRODUCTOS=id_deta;
/*
agregando la referencia a orden de salida en almacen
*/
insert ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS(ID_DETALLE_ALMACEN_PRODUCTOS,ID_CLIENTE,OBSERVACIONES_UBICACION,
FECHA_REGISTRO,CODIGO_FACTURA_BOLETA,CANTIDAD,ID_ESTADO_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS)
values (id_deta,id_cliente,desc_ubicacion, NOW(),concat('VR',NEW.ID_DETALLE_VENTA_RAPIDA_PRODUCTO),_cant,1);


set _resto = _resto - _cant;
else

if id_  = _ID_TIENDA then
update DETALLE_ALMACEN_PRODUCTOS set ID_ESTADO_PRODUCTO_COSTO_ALMACEN=1,SALIERON=SALIERON + _resto,QUEDARON=QUEDARON-_resto
WHERE ID_DETALLE_ALMACEN_PRODUCTOS=id_deta;
/*
agregando la referencia a orden de salida en almacen
*/
insert ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS(ID_DETALLE_ALMACEN_PRODUCTOS,ID_CLIENTE,OBSERVACIONES_UBICACION,
FECHA_REGISTRO,CODIGO_FACTURA_BOLETA,CANTIDAD,ID_ESTADO_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS)
values (id_deta,id_cliente,desc_ubicacion,NOW(),concat('VR',NEW.ID_DETALLE_VENTA_RAPIDA_PRODUCTO),_resto,1);

set _resto=0;
end if;


end if;


  if _resto=0 then
 leave size; 
           
end if;

END LOOP size;
CLOSE c;


END//
DELIMITER ;




DELIMITER //
CREATE TRIGGER elimina_venta_rapida
 BEFORE delete ON DETALLE_VENTA_RAPIDA_PRODUCTO
 FOR EACH ROW
 BEGIN
declare id_ int(11) default 0;

select distinct v.ID_TIENDA into id_ from DETALLE_VENTA_RAPIDA_PRODUCTO dt 
inner join VENTA_RAPIDA v
on dt.ID_VENTA_RAPIDA=v.ID_VENTA_RAPIDA where v.ID_VENTA_RAPIDA=OLD.ID_VENTA_RAPIDA;

UPDATE STOCK_PRODUCTO_TIENDA_ORIGEN AS stk
set stk.CANTIDAD = stk.CANTIDAD+OLD.CANTIDAD
where stk.ID_PRODUCTO = OLD.ID_PRODUCTO and stk.ID_TIENDA_ORIGEN = id_;

/*  TIENES QUE AGERGAR LAS ORDENES DE SALIDA */

END//
DELIMITER ;




CREATE TABLE INVENTARIO_INICIAL_SISTEMA(
ID_INVENTARIO_INICIAL_SISTEMA int(11) NOT NULL AUTO_INCREMENT,
ID_INVENTARIO_FISICO int(11) NOT NULL,
OBERVACIONES VARCHAR(50) NOT NULL DEFAULT "",
FECHA_REGISTRO DATE NOT NULL ,
PRIMARY KEY (ID_INVENTARIO_INICIAL_SISTEMA),
FOREIGN KEY (ID_INVENTARIO_FISICO) REFERENCES INVENTARIO_FISICO (ID_INVENTARIO_FISICO)
)ENGINE=InnoDB;


DELIMITER //
CREATE PROCEDURE RESETEO()
 BEGIN
DELETE FROM DETALLE_ALMACEN_PRODUCTOS WHERE ID_DETALLE_ALMACEN_PRODUCTOS > 0;

/*ALTER TABLE DETALLE_ALMACEN_PRODUCTOS AUTO_INCREMENT = 1;*/

DELETE FROM STOCK_PRODUCTO_TIENDA_ORIGEN WHERE ID_PRODUCTO > 0 and ID_TIENDA_ORIGEN > 0;
DELETE FROM INGRESO_PRODUCTO_TIENDA WHERE ID_INGRESO_PRODUCTO_TIENDA > 0;
DELETE FROM SALIDA_PRODUCTO_TIENDA WHERE ID_SALIDA_PRODUCTO_TIENDA > 0;
DELETE FROM ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS WHERE ID_ORDEN_SALIDA_DETALLE_ALMACEN_PRODUCTOS_COSTOS > 0;

 END //
DELIMITER ;





DELIMITER //
CREATE TRIGGER inserta_inventarios_sistema
 AFTER INSERT ON INVENTARIO_INICIAL_SISTEMA
/*
usa este detalle, para que uses el ID_VENTA, a traves de eso vas a poder actualizar un campo
en la venta que se llame : Utilidad y que sea la resta del costo en almacen entre el precio de venta
*/
 FOR EACH ROW
 BEGIN
declare x int(11) default 0;
declare id_ int(11) default 0;


/*
agregado para las salidas en almacen
*/
DECLARE id_cliente  int(11) default 0;
DECLARE id_producto  int(11) default 0;
DECLARE id_ubicacion int(11) default 0;


DECLARE id_deta  int(50);
DECLARE _cant int(10);
DECLARE _resto int(10);
DECLARE _ID_TIENDA  INT(11);
DECLARE err_no_more_records CONDITION FOR 1329;
DECLARE c CURSOR FOR 


select IFS.ID_INVENTARIO_FISICO as ID,T.ID_TIENDA AS TIENDA, UBF.ID_UBICACION_FISICA AS UBICACION
,P.ID_PRODUCTO AS PRODUCTO, SUM(DUFP.CANTIDAD) as CANTIDAD
from INVENTARIO_FISICO IFS
INNER JOIN DETALLE_INVENTARIO_UBICACION_FISICA DIUF
ON IFS.ID_INVENTARIO_FISICO =DIUF.ID_INVENTARIO_FISICO
INNER JOIN DETALLE_UBICACION_FISICA_PRODUCTO DUFP ON
DIUF.ID_DETALLE_INVENTARIO_UBICACION_FISICA =DUFP.ID_DETALLE_INVENTARIO_UBICACION_FISICA
INNER JOIN TIENDA T ON T.ID_TIENDA =IFS.ID_TIENDA
INNER JOIN UBICACION_FISICA UBF ON UBF.ID_UBICACION_FISICA =DIUF.ID_UBICACION_FISICA
INNER JOIN PRODUCTO P ON P.ID_PRODUCTO=DUFP.ID_PRODUCTO
group by IFS.ID_INVENTARIO_FISICO,T.ID_TIENDA,UBF.ID_UBICACION_FISICA,P.ID_PRODUCTO
having IFS.ID_INVENTARIO_FISICO=new.ID_INVENTARIO_FISICO
ORDER BY 4;


DECLARE EXIT HANDLER FOR err_no_more_records





BEGIN
END;

/* TIENES QUE PONER A RESTEO PARA QUE PRIMARY EMPIESE DESDE 1*/
CALL RESETEO();
OPEN c;

SET x = 0;
size: LOOP
FETCH c INTO id_deta,_ID_TIENDA,id_ubicacion,id_producto,_cant;


INSERT INTO DETALLE_ALMACEN_PRODUCTOS (ID_PRODUCTO,COSTO,ID_TIENDA,CANTIDAD,SALIERON
,QUEDARON,FECHA_INGRESO,FECHA_VENCIMIENTO,DESCRIPCION_MOTIVO,
ID_UBICACION_FISICA,ID_PROCEDENCIA_PRODUCTO_ALMACEN,ID_ESTADO_PRODUCTO_COSTO_ALMACEN)
VALUES(id_producto,0,_ID_TIENDA,_cant,0,_cant,CURDATE(),CURDATE(),'',id_ubicacion,1,1); 

/*UPDATE STOCK_PRODUCTO_TIENDA_ORIGEN AS stk
set stk.CANTIDAD = stk.CANTIDAD + _cant
where stk.ID_PRODUCTO = id_producto and stk.ID_TIENDA_ORIGEN = _ID_TIENDA;
*/

INSERT INTO STOCK_PRODUCTO_TIENDA_ORIGEN
(ID_PRODUCTO,ID_TIENDA_ORIGEN,CANTIDAD,ULTIMA_FECHA_INGRESO,DESCRIPCION)
VALUES
(id_producto,_ID_TIENDA,_cant, curdate(),'')
ON DUPLICATE KEY UPDATE
STOCK_PRODUCTO_TIENDA_ORIGEN.CANTIDAD = STOCK_PRODUCTO_TIENDA_ORIGEN.CANTIDAD + _cant;


/* hay que registrar cada ingreso */
INSERT INTO INGRESO_PRODUCTO_TIENDA(ID_TIENDA,ID_PRODUCTO,CANTIDAD,FECHA_INGRESO,FECHA_VENCIMIENTO
,MOTIVO,ID_UBICACION_FISICA,COSTO_UNITARIO) VALUES (_ID_TIENDA,id_producto,_cant,curdate(),curdate(),'INVENTARIO SISTEMA',
id_ubicacion,0);



END LOOP size;
CLOSE c;


END//
DELIMITER ;



